### ISSUE TITLE
git gutter warns vs. errors are too close in color.

### ISSUE THREAD

**Issue by rhyeen** [Monokai/monokai-pro-sublime-text#10]
Using Python linter and it's near impossible to tell the difference between a warn/error color coding (orange/red).  This makes discovering syntax errors very challenging.

[Link to image](http://imgur.com/leBZaVr)

**Comment by Monokai** [comment]
Do you use [sublimelinter](http://www.sublimelinter.com)? if you do, you should see a cross symbol for errors and a dot for warnings.

**Comment by rhyeen** [comment]
Yes, I'm using SublimeLinter v3.8.0+1 and SublimeLinter-pylint v1.3.2 for this particular linting.  If I choose a non-symbol-based gutter theme, such as **Default - SublimeLinter theme (colorized)** or **Monokai Pro - User theme (colorized)**, then Monokai Pro is overwriting the colors.  If I choose a symbol based theme, then its not overwriting the symbols.

Here is my SublimeLinter.sublime-settings:
```
{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "php": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "phpcs": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "standard": "PSR2"
            },
            "pylint": {
                "@disable": false,
                "args": [],
                "disable": "",
                "enable": "",
                "excludes": [],
                "paths": [],
                "rcfile": "",
                "show-codes": false
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "tooltip_fontsize": "1rem",
        "tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
        "tooltip_theme_excludes": [],
        "tooltips": false,
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

**Comment by Monokai** [comment]
Maybe I don't understand. If you select `command palette > sublime linter: choose gutter theme > monokai pro` it should display a cross for warnings and a dot for warnings. Does this help?

**Comment by dahanbn** [comment]
Didn't know that I can adjust that theme for Sublime Linter as as well.  Is there a similar theme for Git Gutter?

Maybe you list all the possibilites somewhere on the page or on the Monokai Pro install message.  So a user can adjust the themes where you are supporting it.

**Comment by Monokai** [comment]
Git gutter only has colored icons for insert and delete for now. I'll extend this in the next update. I'll also look into how I could make custom (high res) icons.

**Comment by ntwb** [comment]
Wanted to add here that rather than GitGutter I've started using [Modific](https://packagecontrol.io/packages/Modific) as it supports SVN and Git

<img width="224" alt="screen shot 2017-09-19 at 12 59 59 pm" src="https://user-images.githubusercontent.com/1016458/30574002-81541c7a-9d3a-11e7-8d86-0e353807b430.png">


The above image is a test image showing each case showing ESLint status and Git status

Line 13 is an added line (Modific)
Lines 16 is a modified line (Modific)
Line 18 is a removed line (Modific)
Line 21 lint warning (Sublime Linter & Sublime Linter ESLint)
Line 22 lint error (Sublime Linter & Sublime Linter ESLint)

It would be great to have the lint error and lint warnings highlighted with some colors please 😄

**Comment by Monokai** [comment]
I've added a small section with supported plugins in the main readme on how to deal with SublimeLinter and GitGutter: https://github.com/Monokai/monokai-pro-sublime-text#supported-plugins
