### ISSUE TITLE
Blue color to use as "blue" rather than the "orange"?

### ISSUE THREAD

**Issue by ghost** [Monokai/monokai-pro-sublime-text#100]
What blue color code should be used in place of the orange for the Monokai Pro (other variant would be helpful too)?

Thank you!

**Comment by Monokai** [comment]
I don't understand what you mean?

**Comment by ntwb** [comment]
I’d take a guess and suggest this in when using a terminal color scheme and orange is mapped to blue

**Comment by duhok1** [comment]
@Monokai just as @ntwb mentioned!

**Comment by barmadrid** [comment]
Is there a plan to introduce an additional blue color? This would be helpful when working in a terminal. Great theme.

**Comment by kevinsjoberg** [comment]
@Monokai do you have a response here or is the answer as simple as "there's no blue color"? If so, mind closing this usse? 🙂

**Comment by Monokai** [comment]
Terminal colors include a blue and a cyan, and no orange. Monokai Pro only has a cyan-like blue, so it makes sense to map it to cyan. And so I mapped the orange to blue. I admit, it's a bit like pushing a square peg in a round hole, but I haven't found a case yet where it bothered me much.
