### ISSUE TITLE
Color schemes for Sublime Text FileBrowser plugin

### ISSUE THREAD

**Issue by llernestal** [Monokai/monokai-pro-sublime-text#102]
I made some matching color schemes for the [Sublime Text FileBrowser plugin](https://packagecontrol.io/packages/FileBrowser). Can be found here: https://github.com/llernestal/sublime-filebrowser-monokai-pro-color-schemes

Use them if you want them :slightly_smiling_face:

**Comment by kevinsjoberg** [comment]
@Monokai do you want to pursue this? If not, I'd recommend we close the issue.

**Comment by Monokai** [comment]
Thanks for letting me know, appreciate it. For now I'm focusing on the Sublime Text core editor only. Closing for now.
