### ISSUE TITLE
React icon doesn't seem to be working for the .jsx files

### ISSUE THREAD

**Issue by ivansvlv** [Monokai/monokai-pro-sublime-text#103]
*.jsx files render regular JS icon "();" instead of the atom icon of React.

Would be great if you could add another React icon for the *.tsx, and maybe make it a bit darker blue or use the same one as for the *.jsx

**Comment by tsujp** [comment]
+1

**Comment by ivanbanov** [comment]
and the other way around seems to be not working properly as well 😅 
![image](https://user-images.githubusercontent.com/2953018/75250703-3c55d800-57d9-11ea-96f6-e1ef3097ee17.png)

**Comment by kevinsjoberg** [comment]
@Monokai I believe this has been fixed. Close? 🙂

**Comment by aashish108** [comment]
Does not seem to be fixed? JS and JSX files have no icons? Just been trying Monokai Pro out for Sublime Text.

**Comment by aashish108** [comment]
Apologies, its working now! Not sure why it was not before but swapping themes and colours and switching back to this one fixed the issue.
