### ISSUE TITLE
Other type of payment methods

### ISSUE THREAD

**Issue by talgat-ruby** [Monokai/monokai-pro-sublime-text#108]
Hi, thanks for the theme. Can you add other type of payment methods. Yes I know you suggested about guest payment in Paypal. But I think it is true only in EU, because they have a law about privacy of users. For my country maybe the only things the PayPal did not ask, to pee in a cup and send DNA tests. So maybe Patreon?

**Comment by jozefizso** [comment]
PayPal payment method is a bit problematic even in EU, as we cannot set the VAT ID in the purchase.

**Comment by Monokai** [comment]
You can now also pay with credit card (via Stripe)
