### ISSUE TITLE
Color schemes and icons without the theme

### ISSUE THREAD

**Issue by joelcipriano** [Monokai/monokai-pro-sublime-text#109]
Hey, there!

Is it possible to add the option to use one of the Sublime Text 3 default themes (Default or Adaptive) with the Monokai Pro color schemes and the icons? The Monokai Pro Theme is too much different from the defaults ones.

Thanks a lot!

**Comment by gobijan** [comment]
You can combine however you want:
CMD+SHIFT+P => UI: Select Color Scheme and UI: Select Theme.

**Comment by joelcipriano** [comment]
But you don't get the icons without the theme, right? I want the default Adaptive theme, one of the Monokai Pro's colour schemes and the Monokai Pro's icons. Is it possible?

**Comment by Monokai** [comment]
You can mix Sublime themes and schemes as you please, but the idea of Monokai Pro is that it provides a unified user experience. So Monokai Pro treats the Sublime user interface, syntax highlighting and icon package as a whole to provide you with an interface that lets you focus on your code as much as possible.
