### ISSUE TITLE
Are the SublimeLinter settings correct?

### ISSUE THREAD

**Issue by KevinSjoberg** [Monokai/monokai-pro-sublime-text#110]
I've tried to use the settings provided in the README but it does not seem to work correctly. I see a visual difference but no error boundaries around the offending code. I only get a marker for the current line.

Am I doing something wrong?

**Comment by ascendbruce** [comment]
In README, it recommended `none` as the mark style. If you prefer boundaries around the offending code, tweak the `mark_style` to `outline` should do:

```diff
{
	"gutter_theme": "Packages/Theme - Monokai Pro/Monokai Pro.gutter-theme",
	"styles": [
		{
-			"mark_style": "none",
+			"mark_style": "outline",
			"priority": 1,
			"scope": "region.orangish",
			"icon": "warning",
			"types": [
				"warning"
			]
		},
		{
-			"mark_style": "none",
+			"mark_style": "outline",
			"priority": 1,
			"scope": "region.redish",
			"icon": "error",
			"types": [
				"error"
			]
		}
	]
}
```

There are other available styles listed in SublimeLinter's default settings also. For me, I prefer `squiggly_underline` as it's less distracting visually.

**Comment by KevinSjoberg** [comment]
@ascendbruce thank you, appreciate the clarification. 👍
