### ISSUE TITLE
Material Palenight & VSCode Monokai

### ISSUE THREAD

**Issue by tsujp** [Monokai/monokai-pro-sublime-text#111]
Hi there,

I'd like to suggest adding Material Palenight and the option to have VSCode style Monokai syntax highlighting as, in my opinion, it's much much better than all others.

**Comment by Monokai** [comment]
Material Palenight is from a different theme author so I won't include that. This is Monokai Pro. As for the syntax, that's not something I control. I only provide the colorization based on that syntax. The colorization rules are the same for VSCode, but indeed, both editors use different syntax definitions.

**Comment by tsujp** [comment]
I suppose I'll look for a syntax change for ST3, I'll try and grab VSCode's - since asking then and now I prefer the themes in Monokai Pro though so that's fine.
