### ISSUE TITLE
find history drop-down arrow missing

### ISSUE THREAD

**Issue by godey4me** [Monokai/monokai-pro-sublime-text#112]
Hi,
The drop arrow used to select find history is broken in this theme. See image
![2019-10-10_12-09-28](https://user-images.githubusercontent.com/19440061/66595200-b6056600-eb57-11e9-8013-e5143dde908e.png)

The issue has been present for sometime. Can we get a fix?
Thanks
ST3, windows 10

**Comment by Monokai** [comment]
fixed in 1.1.15
