### ISSUE TITLE
Color Highlight works badly 

### ISSUE THREAD

**Issue by clementgalliot** [Monokai/monokai-pro-sublime-text#113]
Hello,
Great theme but i can't use original color schemes (that i like a lot !! :o) because in my work i have to use Color Highlight plugin : 

- With any Monokai Pro color scheme : 

![image](https://user-images.githubusercontent.com/37953255/67304889-cc66d680-f4f4-11e9-8159-c3a282ec2243.png)

- With MaterialMonokaiBlue (that I use replacing... ) : 

![image](https://user-images.githubusercontent.com/37953255/67305069-1780e980-f4f5-11e9-9cda-a21fd1ba25e9.png)

An idea to fix it ?

Thank you

**Comment by Monokai** [comment]
I tried to install the plugin but it doesn't work and I'm getting errors from this plugin in my console. I think it's best to create an issue at the repository of Color Highlight.

I'm using Color Helper for showing colors. It puts a square in front of the hex value. Keeps the text legible.

**Comment by Fendriz** [comment]
I got the same problem.
