### ISSUE TITLE
Font clips for a newly opened file.

### ISSUE THREAD

**Issue by mrillusi0n** [Monokai/monokai-pro-sublime-text#114]
![image](https://user-images.githubusercontent.com/37063502/70640572-261c8f00-1c62-11ea-9c78-337eee3838b5.png)

**Comment by Monokai** [comment]
I cannot reproduce this. I remember there were some ST3 rendering bugs with certain fonts. Which font are you using?

**Comment by dndrsn** [comment]
I just encountered this issue.  This happens when using Fira Code as the UI font face -- https://github.com/tonsky/FiraCode.  Only occurs when the tab text is italicized.

**Comment by mrillusi0n** [comment]
> I cannot reproduce this. I remember there were some ST3 rendering bugs with certain fonts. Which font are you using?

Fira Code.

**Comment by Monokai** [comment]
Have you let Sublime know? i think it's a font rendering bug. Most fonts don't seem to have a problem.
