### ISSUE TITLE
UI theme doesn't seem to exist

### ISSUE THREAD

**Issue by NetOperatorWibby** [Monokai/monokai-pro-sublime-text#115]
I don't see it in the `Theme...` menu section. All of the `Color Scheme...`s show up fine. I thought I needed to purchase a license in order to enable it but alas.

**Comment by NetOperatorWibby** [comment]
Thanks to #24 and the snippet of configuration settings I was able to test manually changing the UI theme that way:

```
"theme": "Monokai Pro (Filter Octagon).sublime-theme",
```

Doing this for all the themes allowed them to then appear in the command palette. For other with this issue, here's a list of UI themes to manually enter:

- `Monokai Pro (Filter Machine).sublime-theme`
- `Monokai Pro (Filter Octagon).sublime-theme`
- `Monokai Pro (Filter Ristrotto).sublime-theme`
- `Monokai Pro (Filter Spectrum).sublime-theme`

**Comment by Monokai** [comment]
Please use the command `Monokai Pro: select theme` instead of `UI: select theme`. When you use the first command, it also selects the matching icon set and color scheme.
