### ISSUE TITLE
Disabling or removing the package breaks Sublime Text UI

### ISSUE THREAD

**Issue by IAmAdamTaylor** [Monokai/monokai-pro-sublime-text#116]
When the package is disabled or removed the whole of the Sublime Text UI is affected, causing certain interface elements to appear broken.

See this screenshot:
![Sublime with Monokai Pro disabled](https://user-images.githubusercontent.com/15825217/72910321-485cfe80-3d30-11ea-9e45-7ab88698f61f.png)

The tab bar, command palette, sidebar icons, scroll bar and find and replace interface are all affected. The font and color used by the interface also remain as the mono font and yellow colour, instead of switching back to the default Sublime Text UI.

**What I would expect**

Disabling the package or removing it switches back to the default Sublime Text UI, as if the package hadn't been installed.

**Comment by IAmAdamTaylor** [comment]
Figured it out. 

I assumed this package only installed as a Color Scheme - instead it installs a separate UI Theme, which I didn't know Sublime Text supported.

**To switch back to the default Sublime Text UI:**
Command Palette (Cmd + Shift + P / Ctrl + Shift + P) -> UI: Select Theme -> Adaptive.sublime-theme

You can then continue to use the Monokai Pro color schemes if you want with:
Command Palette (Cmd + Shift + P / Ctrl + Shift + P) -> UI: Select Color Scheme

Alternatively, you can disable and remove the package entirely after this without breaking the interface.

**Comment by oliverhr** [comment]
Just as an annotation, removing the package with "control package: remove package" leave with this issue you need to manually remove the directory, to not end with residual effects.
