### ISSUE TITLE
Switching theme in ST4 causes UI glitch

### ISSUE THREAD

**Issue by KevinSjoberg** [Monokai/monokai-pro-sublime-text#118]
👋 @Monokai 

First of all, a huge thank you for all work you've put into Monokai Pro. I've been using it since the start and it's a really pleasant experience, especially together with the themes for Terminal.app.

So, I'm using ST4 (not officially released yet) and switching Monokai Pro theme using "Monokai Pro: select theme" causes a weird render glitch. The behaviour can be corrected by restarting Sublime Text altogether.

See the video below for a demonstration.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/503025/73481643-898e8780-439c-11ea-8695-c1cbba725cd4.gif)

The issue only occur the very first time you select the theme, future selection for the same theme will not cause this glitch. Even after further restarts.

If you don't already have ST4, I'd be happy to send you a link for your operating system so you could debug this issue.

If you need anything else, I'd be happy to help out.

**Comment by Monokai** [comment]
I'm seeing this too, but it's unpredictable. Sometimes it works, sometimes not. Maybe ST4 changed the theming system, but I haven't seen any new docs yet. Hard to determine if I need to solve anything or ST4 simply has a bug. Have you let Sublime know?

**Comment by KevinSjoberg** [comment]
@Monokai I have and they said they could look into it given they have access to the source. Perhaps you could provide them with that?

**Comment by Monokai** [comment]
Do you have a link to a Github issue?

**Comment by KevinSjoberg** [comment]
I think this was a discussion we had in their Discord, so no formal issue was ever formed in their issue tracker. Do you want me to file an issue and report back here?

**Comment by Monokai** [comment]
would be nice, thanks!

**Comment by Monokai** [comment]
closing for now
