### ISSUE TITLE
Python Variable highlighted as Method

### ISSUE THREAD

**Issue by andyxukq** [Monokai/monokai-pro-sublime-text#119]
Hi Monokai!
I'm using ST3 latest build 3211. Seems there's an issue with Monokai Pro rendering variable name as method, see the variable `collection`:
<img width="258" alt="Screen Shot 2020-03-02 at 12 02 42 PM" src="https://user-images.githubusercontent.com/3887449/75713010-d7d5c580-5c7d-11ea-9282-f8ae465c20ac.png">

I verified that all built-in color schemes (including the built-in Monokai color) don't have this issue. Is this intended behavior? Could you let me know how to change it? Thanks!

**Comment by andyxukq** [comment]
<img width="758" alt="Screen Shot 2020-03-02 at 12 33 26 PM" src="https://user-images.githubusercontent.com/3887449/75715663-a1e71000-5c82-11ea-93ed-1a83788a2301.png">
<img width="579" alt="Screen Shot 2020-03-02 at 12 33 49 PM" src="https://user-images.githubusercontent.com/3887449/75715666-a4496a00-5c82-11ea-97ad-594b76ce3006.png">
I noticed these two grammar error in the color scheme file, I believe the first one is causing the issue, not sure about the second one but it looks worth fixing.

**Comment by Monokai** [comment]
Fixed in 1.1.16
