### ISSUE TITLE
ST4: UI Refinements needed

### ISSUE THREAD

**Issue by gobijan** [Monokai/monokai-pro-sublime-text#122]
- The toggle sidebar button in the lower left needs some treatment. Currently it's black.
- When using "Find All" the new include git button is not working properly.

**Comment by gobijan** [comment]
Both problems on a screenshot.

<img width="324" alt="Bildschirmfoto 2020-05-09 um 10 21 45" src="https://user-images.githubusercontent.com/49339/81468304-e4771c80-91de-11ea-8618-7368c95f3243.png">

**Comment by gobijan** [comment]
I fixed it for me locally but I don't know how to contribute to this project since it's private :/

**Comment by Monokai** [comment]
Added new icons for ST4 in 1.1.16

**Comment by gobijan** [comment]
Perfect. Thx so much :)
