### ISSUE TITLE
'async' to match 'await' highlighting?

### ISSUE THREAD

**Issue by dwhenson** [Monokai/monokai-pro-sublime-text#123]
Small point but it would be really nice if the highlight color for 'async' matches that for 'await' as it currently does in VS Code. Not a big deal but just makes is so much easier when scanning code. At the moment 'async' is just the same color as the following 'function'.

**Comment by Monokai** [comment]
The colors depend on the syntax definitions of each editor. I've tried to make them the same, but it's not always possible.

In Sublime Text `async` is marked as `storage.type` and `await` as `keyword.control.flow`. So in Sublime Text `async` conceptually is a type of function, and `await` is a keyword to make sure the control flow of your program waits for a promise to resolve. There are other storage types like `const` for example. Styling one affects the other.

VSCode has a different type for `async` keywords: `storage.modifier.async`. This is more specific, so you can alter this color without affecting the other storage modifiers. Currently this doesn't seem possible in Sublime Text

**Comment by dwhenson** [comment]
Thanks for looking into it all the same. Much appreciated!
