### ISSUE TITLE
How to change the default color of brackets, parenthesis and all of those??

### ISSUE THREAD

**Issue by PranavDhamanage** [Monokai/monokai-pro-sublime-text#124]
I tried a number of different ways to do that but no success.
I don't want the color of brackets to change when the caret is near on not. I want its default color to change. But there seems no option to change the color in monokai pro file when opened with PackageResourceViewer.

**Comment by keithrussell42** [comment]
I've been having a hard time with this as well. I've found that it's hard with my chosen font (Pragmata Pro) to distinguish `}` and `)` when they are close together. I can do this with no problem in a light theme (black text on white background) or the default Mariana theme (bold white for parens and braces). I find the lack of contrast to be the issue. I would love an option to make the punctuation have a bit more contrast.

**Comment by Monokai** [comment]
@PranavDhamanage My theme does not change the parentheses when the caret is near, I'm not sure what you mean?

@keithrussell42 it's hard to create something that satisfies everybody. If I would increase the contrast, others would like it to decrease again :) If you want a bit more clarity, filter Spectrum has the most contrast.

**Comment by kevinsjoberg** [comment]
I think we can close this for for, @Monokai.
