### ISSUE TITLE
error loading theme at loading sublime

### ISSUE THREAD

**Issue by boistordu** [Monokai/monokai-pro-sublime-text#125]
Hi,

I want to clear things up. Is there any URL that your package is contacting at loading up?

**Comment by Monokai** [comment]
The code inside my theme doesn't contact any URL on startup. Only when you click in the popup, then you'll navigate to https://monokai.pro.

Why are you asking?

**Comment by boistordu** [comment]
Well if I don't have internet or only a dns link then the theme is not loading and there are a lot of errors popping up

**Comment by boistordu** [comment]
here for example on a host that I just reboot after a windows update that is fully connected to internet but indeed with some dns filtering so I do'nt know if it's related 

![monokaiproAnnotation 2020-06-09 202349](https://user-images.githubusercontent.com/9523075/84196117-44d3d500-aa8f-11ea-9431-da44ce7542ad.png)

**Comment by Shura1oplot** [comment]
I got the same error. https://monokai.pro/ is unavailable from Russia.

**Comment by Monokai** [comment]
I think both issues are unrelated to monokai.pro. I don't ping any URLs in my code and I don't block any specific countries on https://monokai.pro (might be ISP related?)

**Comment by Monokai** [comment]
That's unfortunate. I've tried some ping testers and DNS checkers online, but they all resolve. Do you have a link to a service that gives errors from Russia & Japan?

**Comment by Shura1oplot** [comment]
Yes, here they are:

1. Russia: https://check-host.net/check-http?host=monokai.pro
I checked monokai.pro ip address (188.166.30.68) and it is blocked in Russia:
https://isitblockedinrussia.com/?host=188.166.30.68

2. Japan: https://www.uptimia.com/website-availability-test
I see all hosts inaccessible from Japan in uptimia.com, so monokai.pro is fine there.

**Comment by boistordu** [comment]
anyway, since it is most probably a problam about the updating from the package maanger, is it possible to resolve on your end in your code to actually store the theme even when it is updated or maybe moved somewhere as a fallback, and maybe add a if or something alike?
your website is actually blocked by many blocklist used by nextdns.io or pihole or other

**Comment by boistordu** [comment]
and it would be useful also in cas of your server is offline for whatever reason, because of ddos or anything alike

**Comment by Shura1oplot** [comment]
There are 3 possible solutions:
1. Create an issue for sublime package manager and wait until it will be fixed
2. Move the distribution of monokai packages to GitHub
3. Do something with the website to unblock it

As a temporary solution I would suggest to update sublime packages using VPN and than to disable automatic updates.

**Comment by boistordu** [comment]
I didn't look how the package manager is working. So there would be no by-pass to how the package is stored or anything? 
For my blocklist it wasn't that apparently since it was already whitelisted. I guess a temporary down from the routes or anything like that. Is there any open tickets about that on sublime packager?

**Comment by Monokai** [comment]
I've moved my server to another IP just in case. Maybe that helps.

**Comment by Shura1oplot** [comment]
Problem solved for me.

**Comment by benfrain** [comment]
Just to add that if you add the following extra keys to your package control settings you can prevent the issues if you are behind a limited access environment:

```
    "auto_upgrade": false,
    "submit_usage": false,
    "remove_orphaned": false,
```
