### ISSUE TITLE
How about an adaptive variant

### ISSUE THREAD

**Issue by gobijan** [Monokai/monokai-pro-sublime-text#126]
Hi I really really like the UI Theme. When it comes to color schemes I am often switching to my likings. Unfortunately the awesome UI Theme then often no longer matches the background color of my color scheme. 

Would it be feasible to create an adaptive theme variant that behaves similar to the built in adaptive theme?

**Comment by Monokai** [comment]
Back when I started this theme, I've decided to design it as an integrated whole. Colors, icons, UI elements. The colors and UI elements are precisely controlled by a single theme. I'm offering 5 filters for different moods.

The adaptive theme lets go of some of these elements and while it often works well, I don't consider it Monokai Pro anymore. So at least for now I won't put effort into supporting adaptive theming.

**Comment by gobijan** [comment]
Hi Wimer, okay I understand and respect that.
