### ISSUE TITLE
[ST4]"show_tab_close_buttons_on_left": true doesn't work

### ISSUE THREAD

**Issue by Jax0rz** [Monokai/monokai-pro-sublime-text#129]
ST4 introduced a new method called “show_tab_close_buttons_on_left”,which can make the tab close button to the left on macOS.This feature makes sublime text more native on macOS.I found it works with the default theme, but it doesn’t work with Monokai Pro.

**Comment by Monokai** [comment]
added in 1.1.18

**Comment by Jax0rz** [comment]
> added in 1.1.18

Thanks,Awesome

**Comment by Jax0rz** [comment]
Thanks man ,you make my sublime text so fancy and native.
<img width="1384" alt="CleanShot 2020-11-24 at 21 17 42@2x" src="https://user-images.githubusercontent.com/7557357/100099624-ab607a00-2e9a-11eb-97e3-68608dc57fce.png">
<img width="1384" alt="CleanShot 2020-11-24 at 21 18 02@2x" src="https://user-images.githubusercontent.com/7557357/100099632-ae5b6a80-2e9a-11eb-823b-8fee1bb2f1c2.png">
