### ISSUE TITLE
atom package

### ISSUE THREAD

**Issue by cuni0716** [Monokai/monokai-pro-sublime-text#13]
I think that the world needs this beautifull syntax for the atom editor, can i help you???

**Comment by Monokai** [comment]
Thanks for your offer :) I'm going to have a look myself first. Maybe I'll come back to you.

**Comment by iamchriswick** [comment]
Any news on this @Monokai ?

**Comment by yunusemrecan** [comment]
Any update on atom package @Monokai ?

**Comment by MicheleBertoli** [comment]
Yes, please!

**Comment by splodingsocks** [comment]
I'd love to pay money again for the atom theme. I purchased the VS Code theme last year and I've loved it.
