### ISSUE TITLE
packages.monokai.pro not found

### ISSUE THREAD

**Issue by neilgupta** [Monokai/monokai-pro-sublime-text#130]
It looks like `Theme - Monokai Pro` is no longer listed in Sublime Text's package manager because packages.monokai.pro is returning a 404 not found.

See `missing` error at the top of https://packagecontrol.io/packages/Theme%20-%20Monokai%20Pro

Is this a temporary downtime or a permanent removal? As of this comment, the package was available 11 hours ago, so I'm guessing this is a bug.

**Comment by rtzll** [comment]
I noticed that it's available again. :man_shrugging: :tada:

**Comment by michael-j-terry** [comment]
Issue persists, currently unavailable on Package Control.

**Comment by pranjalyadav451** [comment]
![image](https://user-images.githubusercontent.com/64234973/141791474-4b6113f5-dd55-443d-befd-3d0120e7b528.png)
Still not available
