### ISSUE TITLE
Link coloring (e.g. Command Palette - Install Packages) broken for ST4

### ISSUE THREAD

**Issue by gb4711de** [Monokai/monokai-pro-sublime-text#131]
See discussion on the ST Discord channel:
https://discord.com/channels/280102180189634562/280102180189634562/768956239891529738

Possibly a color-scheme thing?

**Comment by gb4711de** [comment]
the following link offers a solution to this problem:
https://github.com/sublimehq/sublime_text/issues/3697

**Comment by KevinSjoberg** [comment]
Yeah, I'm seeing the same thing on a fresh install of ST4 with any of the Monokai Pro themes.

<img width="852" alt="Screenshot 2020-12-13 at 09 17 29" src="https://user-images.githubusercontent.com/503025/102006777-06f88780-3d24-11eb-8df9-878a1e45636e.png">

**Comment by Monokai** [comment]
fixed in 1.1.19

**Comment by kevinsjoberg** [comment]
Thank you! ❤️
