### ISSUE TITLE
Number of items displayed when using Ctrl+P and Ctrl+Shift+P in Sublime Text 4

### ISSUE THREAD

**Issue by fgimian** [Monokai/monokai-pro-sublime-text#135]
Hey there, stunning theme, absolutely love it.

I realise Sublime Text 4 is in alpha but thought I'd raise this in case it can be solved.

My main issue is that far less items show up using this theme when using Ctrl+P and Ctrl+Shift+P compared to regular themes.

e.g. Adaptive vs Monokai Pro Ctrl+P

![image](https://user-images.githubusercontent.com/1811813/102579976-c056c300-4151-11eb-90ab-f61824821398.png)

![image](https://user-images.githubusercontent.com/1811813/102579994-cba9ee80-4151-11eb-91c6-71034abad539.png)

e.g. Adaptive vs Monokai Pro Ctrl+Shift+P

![image](https://user-images.githubusercontent.com/1811813/102580030-dc5a6480-4151-11eb-9e5c-c17747483ef2.png)

![image](https://user-images.githubusercontent.com/1811813/102580036-e1b7af00-4151-11eb-9c93-1f1413121228.png)

This does not appear to be an issue in Sublime Text 3.

Thanks heaps
Fotis

**Comment by Monokai** [comment]
This is something that is controlled by the editor and it's not something I have control over unfortunately.
