### ISSUE TITLE
ST4: Folder arrows are black.

### ISSUE THREAD

**Issue by gobijan** [Monokai/monokai-pro-sublime-text#137]
<img width="1505" alt="Bildschirmfoto 2021-02-01 um 21 56 49" src="https://user-images.githubusercontent.com/49339/106517161-667b4400-64d8-11eb-99f1-07415c840eb0.png">

**Comment by Jax0rz** [comment]
The problem is solved in ST 4098,so I think this is a ST 4 bug.
