### ISSUE TITLE
The main window scroll bars have wrong colour

### ISSUE THREAD

**Issue by orangecoloured** [Monokai/monokai-pro-sublime-text#138]
I have latest macOS Big Sur and the latest ST4 build.

<img width="1440" alt="Screenshot 2021-02-16 at 23 10 52" src="https://user-images.githubusercontent.com/3314891/108121959-3cb34700-70ac-11eb-9bb1-024270d11e67.png">

In the screenshot in the bottom right there's a white square. In the left sidebar that square is dark. It appears only when a horizontal scroller appears.
I think it makes sense to make these corners the same color as the scrollbars background.

**Comment by Monokai** [comment]
fixed in 1.1.19
