### ISSUE TITLE
VS Code version

### ISSUE THREAD

**Issue by uikid** [Monokai/monokai-pro-sublime-text#14]
Since the development is lagging more and more and other editors like VS Code are getting faster with each release, it should be considered to create the theme for VS Code.

One benefit could be: VS Code is free, maybe more people are willing to pay for a nice theme. I would, if it would be available.

**Comment by Monokai** [comment]
Here's [the official Visual Studio Code Monokai Pro theme](https://marketplace.visualstudio.com/items?itemName=monokai.theme-monokai-pro-vscode)

And here's [the Github issues repo](https://github.com/Monokai/monokai-pro-vscode) for the VSCode version.
