### ISSUE TITLE
Can't find where to enter license key in ST4? Please advise

### ISSUE THREAD

**Issue by dwhenson** [Monokai/monokai-pro-sublime-text#140]

**Comment by Monokai** [comment]
Please check your license email and follow its instructions. Should work in ST4 as well.

**Comment by dwhenson** [comment]
I searched for "Monokai Pro: enter license" but nothing shows up at the moment.

**Comment by Monokai** [comment]
Have you installed the package? It's called "Theme - Monokai Pro".

**Comment by dwhenson** [comment]
Yes, absolutely! I attached a screenshot of what I see when I search.. I had no problems adding under ST3
<img width="1353" alt="Screenshot 2021-04-06 at 11 36 32" src="https://user-images.githubusercontent.com/50716370/113683094-7d066d00-96cc-11eb-9399-00628e68e726.png">

**Comment by Monokai** [comment]
Did you perhaps purchase the VSCode version? Entering a license in Sublime Text works differently from VSCode. In VSCode there's an "enter license" item, but not in Sublime Text. What does the license email say?

**Comment by dwhenson** [comment]
Yes! That's it I bought the VS Code version. So sorry to have wasted your time!! Do I need to buy another licence for Sublime?

**Comment by lzaaldian** [comment]
> Yes! That's it I bought the VS Code version. So sorry to have wasted your time!! Do I need to buy another licence for Sublime?

I believe you have to buy the license for Sublime Text. You can't open a door with the wrong key, right? 😄

As the author @Monokai said, you can find the instruction in the email.

<img width="841" alt="Jepretan Layar 2021-08-22 pukul 2 29 07 PM" src="https://user-images.githubusercontent.com/3760093/130346466-0e33a839-92cb-4575-817f-5ad87e2052e3.png">

**Comment by dwhenson** [comment]
OK thanks I guess I thought it would work per person rather than per editor. No problem.
