### ISSUE TITLE
Format specifiers in C are not highlighted properly

### ISSUE THREAD

**Issue by kevinsjoberg** [Monokai/monokai-pro-sublime-text#141]
In C, you can use format specifiers in the string provided to `printf`. They're followed the following format:

```
%[flags][width][.precision][length]specifier
```

**Mariana (default theme)**

<img width="499" alt="Screenshot 2021-04-06 at 12 32 35" src="https://user-images.githubusercontent.com/503025/113698022-4e8c9000-96d4-11eb-9fd0-d370e03d444b.png">

**Monokai Pro**

<img width="499" alt="Screenshot 2021-04-06 at 12 32 23" src="https://user-images.githubusercontent.com/503025/113698052-564c3480-96d4-11eb-9993-d1e5f68ec776.png">

By the looks of it, they're categorised under the scope `constant.other.placeholder.c`.

<img width="267" alt="Screenshot 2021-04-06 at 12 35 11" src="https://user-images.githubusercontent.com/503025/113698249-8abff080-96d4-11eb-918b-d1c8a3fc6119.png">

**Comment by Monokai** [comment]
fixed in 1.1.20
