### ISSUE TITLE
license notification

### ISSUE THREAD

**Issue by zanuka** [Monokai/monokai-pro-sublime-text#145]
Why do I keep getting a license notification request in Sublime Text for the Monokai Pro theme when I have entered my paid license? It also happens in VSCode with a paid license.

**Comment by Monokai** [comment]
If you've entered your license info, it should trigger the popup anymore. Are you sure you've copy-pasted the info correctly?

**Comment by kevinsjoberg** [comment]
@Monokai I think we can close this for now.
