### ISSUE TITLE
Find/Replace a bit off

### ISSUE THREAD

**Issue by ivanbanov** [Monokai/monokai-pro-sublime-text#146]
On SublimeText 4 the find-replace is a bit off

![image](https://user-images.githubusercontent.com/2953018/136761685-b3b69a67-b951-4398-bd2a-27014ac88b66.png)

**Comment by Monokai** [comment]
This is not how it's supposed to look, but I can't replicate. could you please switch to a different Monokai Pro filter and back again?

**Comment by ivanbanov** [comment]
Oh, I forgot to close this one, it was fixed some time ago, probably some bad config from my side.
Sorry for the noise
