### ISSUE TITLE
Monokai PRO 

### ISSUE THREAD

**Issue by Cryptronxidotcom** [Monokai/monokai-pro-sublime-text#148]
I followed these instructions and I do not see a drop down or any indication a menu is on your site titled Preference menu?!?

Select option also was not see or distinctly indicated, no way this instruction matched anything on your site! WOW! Simple to add a few or one drop list or window with these instructional title - description... Please fix your webpage, oh and tell me where is this select option??? none seen at this time...   The only active area on this website is the purchase controls... wow... disappointed as a blockchain developer... 

Thanks for your purchase of Monokai Pro for Sublime Text. Please follow these instructions to activate your license:

1. Go to the Sublime Text Preferences menu
2. Select "Package Settings" > "Theme - Monokai Pro" > "Settings - User"
3. Add the following text and save the file:
???

**Comment by Monokai** [comment]
You can find the settings via the Sublime Text menu. I've added a screenshot below.

<img width="825" alt="Screen Shot 2022-01-19 at 20 09 08" src="https://user-images.githubusercontent.com/277589/150197983-45d0183e-fe27-4a98-b6a2-860f5c81f28c.png">
