### ISSUE TITLE
In Markdown, please add italics, bold, and blockquote styles.

### ISSUE THREAD

**Issue by pastorryanhayden** [Monokai/monokai-pro-sublime-text#15]
I love Monokai Pro and have paid for a license.  The one thing I miss over Cobalt2 is the bold, italic and blockquote styles in Markdown.

![screen shot 2017-07-26 at 2 07 25 pm](https://user-images.githubusercontent.com/4194905/28638848-c974f060-720b-11e7-972e-a12a0bb3cc9f.png)

**Comment by Monokai** [comment]
Added italics and block quote styles. Bold is yellow, and not actual bold, because bold font rendering sometimes looks bad with certain fonts in Sublime Text. As bold is nowhere used (yet), I opted for yellow for now.

**Comment by dahanbn** [comment]
The colored rendering is really appreciated. Especially that yellow is one of my favourites. But please make bold optional. I would like to have the bold markup in yellow & bold.
