### ISSUE TITLE
Bug in the colorization

### ISSUE THREAD

**Issue by rarodja** [Monokai/monokai-pro-sublime-text#154]
As also happens in the theme for VSCode, in Sublime Text the same thing happens in the style tag, it is not colored green like the class tag

![sublimetext](https://user-images.githubusercontent.com/74628132/163835275-2723d761-5d4c-4d39-b703-4655fa323069.png)

**Comment by Monokai** [comment]
The syntax definitions of this piece of code are based on styled css. It might be viewed as inconsistent from a html viewpoint: they're both string values of an html attribute, but it does help to make things clearer from a css viewpoint: within this specific string you also have css key-value pairs. Not sure if I could edit this in a color theme, as they depend on the syntax definitions of Sublime Text, but even if I could, I think how it is now is fine.
