### ISSUE TITLE
Add support for ''draw_active_single" Sublime preference

### ISSUE THREAD

**Issue by benfrain** [Monokai/monokai-pro-sublime-text#156]
In ST4 there is a preference for `"indent_guide_options"` which I have set to `["draw_active", "solid", "draw_active_single"],`

With a standard ST theme this renders the active indent guide a brighter color than the other indent guides. With this theme it has no effect.

Could you amend the theme to respect this setting?

**Comment by Monokai** [comment]
Maybe I misunderstand. @benfrain can you post a screenshot and the name of the color scheme you're using? I think `draw_active_single` only displays the active guide instead of all its parents. In that sense, `draw_active` and `draw_active_single` seem mutually exclusive.

**Comment by benfrain** [comment]
Hi,

Sure, with those settings, here is Monokai Pro:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/1318466/186761678-10802317-7b65-466a-b009-61d55b7b1381.png">

And here is the default theme (Mariana):

<img width="615" alt="image" src="https://user-images.githubusercontent.com/1318466/186762312-794555a8-789b-498f-b88b-a4f3c67a9e35.png">

Notice the brighter line at the current indent level using Mariana?

**Comment by Monokai** [comment]
This finally works. I didn't understand what went wrong all this time, but I had `activeGuide` and `stackGuide` incorrectly camel-cased instead of `active_guide` and `stack_guide`.
