### ISSUE TITLE
Invisible auto complete labels with `Adaptive` theme due to foreground hack

### ISSUE THREAD

**Issue by ihodev** [Monokai/monokai-pro-sublime-text#16]
I've seen that your color schemes use next [hack](https://github.com/icylace/CursorRuler/wiki/Tips#ruler-colors) to adjust color of the rulers, but it causes next [issue](https://github.com/SublimeTextIssues/Core/issues/1830) when the user uses `Monokai Pro` color scheme and default `Adaptive` theme. Hope you could remove it and wait when ST devs add support for theming such UI elements.

Thanks!

P.S. Amazing colors :heart:

**Comment by Monokai** [comment]
@ihodev Ah, that's unfortunate. One question: can you elaborate more on why you enable the Adaptive theme after installing Monokai Pro?

**Comment by ihodev** [comment]
@Monokai That's because I like a lot your color schemes, but `Adaptive` UI theme fits better my needs.

**Comment by Monokai** [comment]
I don't see what Adaptive solves that Monokai Pro doesn't solve at the moment, so I think I have to keep this (admittedly ugly) hack. As soon as Sublime Text has a dedicated option for the rulers, I'll implement that and remove the hack.
