### ISSUE TITLE
Markdown link punctuation colored differently

### ISSUE THREAD

**Issue by brandonchinn178** [Monokai/monokai-pro-sublime-text#160]
In newer ST upgrade (same time as #159), punctuation in markdown links are styled differently:

Current:
![Screen Shot 2022-12-03 at 7 07 37 PM](https://user-images.githubusercontent.com/6827922/205472303-2004c75c-1c7f-4b05-96f0-cf2d517f6bc2.png)

Desired:
![Screen Shot 2022-12-03 at 7 06 55 PM](https://user-images.githubusercontent.com/6827922/205472292-54130e05-e30d-43ec-b68e-9da5e70b4f6b.png)

Workaround:
```json
{
  "name": "Markdown: links",
  "scope": "markup.underline.link punctuation",
  "foreground": "#a9dc76",
},
```

**Comment by Monokai** [comment]
Thanks, Fixed in 1.2.1.
