### ISSUE TITLE
Hide Text and Icon in Title bar?

### ISSUE THREAD

**Issue by dwhenson** [Monokai/monokai-pro-sublime-text#161]
I'd love to hide the text and icon in the title bar to complete a really minimal look.

At the moment I've set the file title text to be the same color as the background, so it appears invisible, but I can't hide the icon. Could the theme take care of this somehow, or any suggestions on how to hide the file icon?

I've attached a screenshot below here you can see the annoying white square file icon that I want rid of! I've tried all the settings I can think of (and I love this theme and color scheme thanks!)

<img width="1021" alt="annoying" src="https://user-images.githubusercontent.com/50716370/210000676-528a259a-204f-4dd6-a91c-02e8978651f5.png">

**Comment by dwhenson** [comment]
I see the issue was moved here from Sublime so I’ll close this one

**Comment by Monokai** [comment]
I think this is a MacOS specific thing that can't be controlled via a theme, maybe ask here? http://github.com/sublimehq/sublime_text/issues
