### ISSUE TITLE
Issue with text background using Terminus package.

### ISSUE THREAD

**Issue by sukinoverse** [Monokai/monokai-pro-sublime-text#162]
### Setup
- macOS Ventura 13.2
- Sublime Text 4 (Build 4147)
- Monokai Pro 1.2.0
- Terminus Package

### Problem
- Terminus with Monokai Pro theme has contrast background color between some text and the terminal background.
- For example, `git init .` and `git status` command, you'll see different in a text background.

Please see screenshots compared between default Mariana theme vs Monokai Pro.

#### Monokai Pro
<img width="1381" alt="Screenshot 2023-02-05 at 14 48 08" src="https://user-images.githubusercontent.com/9070844/216807780-fbcf2b36-6b64-4ead-87ee-093e5342fff1.png">

#### Default Mariana
<img width="1381" alt="Screenshot 2023-02-05 at 14 52 20" src="https://user-images.githubusercontent.com/9070844/216807861-d2e3b5eb-0cef-47ed-a16c-e7c94e06ec4e.png">

**Comment by Monokai** [comment]
I think this is Terminus specific. Maybe ask them for an option to disable background colors?
