### ISSUE TITLE
Would it be possible to support for Sublime Text 4 Adaptive Theme?

### ISSUE THREAD

**Issue by sukinoverse** [Monokai/monokai-pro-sublime-text#163]
### Setup
- macOS Ventura 13.2
- Sublime Text 4 (Build 4147)
- Monokai Pro 1.2.0

### Description
Would like to request Monokai Pro to support Sublime Text 4 Adaptive Theme.

### Why?
Someone like me using light mode on macOS, so with default Theme and Color Scheme from a Monokai Pro, I'll get a light title bar. This cause a contrast between color scheme and the windows' title bar.

However, with Sublime Text 4's new Adaptive Theme will match title bar color with the color scheme.
   - But Monokai Pro customization for sidebar will be lost (font, icons and etc.) :(
   - So, I would like to keep title bar color match with the color scheme (like ST Adaptive theme) but also have Monokai Pro Sidebar Theme. Is that possible?

#### Monokai Pro Theme + Monokai Pro Color Scheme
<img width="1381" alt="Screenshot 2023-02-05 at 15 04 09" src="https://user-images.githubusercontent.com/9070844/216808463-8e3be30a-49f9-447a-bdaa-d8a3de2f7c19.png">

#### Sublime Text 4 Adaptive Theme + Monokai Pro Color Scheme
<img width="1381" alt="Screenshot 2023-02-05 at 15 04 47" src="https://user-images.githubusercontent.com/9070844/216808494-494b3830-1e06-4cae-9840-5fb13925f773.png">

**Comment by Monokai** [comment]
You could add this to your settings:

`"monokai_pro_style_title_bar": true` which sets the title bar to a color that matches the theme.
