### ISSUE TITLE
Adaptive Theme

### ISSUE THREAD

**Issue by gobijan** [Monokai/monokai-pro-sublime-text#167]
I love the UI Theme.
Sometimes I switch to a light theme or a theme I created or customized.
Did you consider offering an adaptive version of your theme? So the colors would not be hard coded and instead be deducted from the color scheme.
I custimized the adaptive theme and the Da Neo Theme to look more like Monokai Pro but I can't tell you how happy an adaptive version would make me.
Any chance you might do that?

**Comment by gobijan** [comment]
Sorry I've just seen that I requested this earlier in 2020. Sry.

**Comment by Monokai** [comment]
Monokai Pro 2.0 has a light version now

**Comment by gobijan** [comment]
Yaaaaay! I'm celebrating ;D
