### ISSUE TITLE
Background for generated packages covers their name - Intellij IDEA

### ISSUE THREAD

**Issue by PiotrMur** [Monokai/monokai-pro-sublime-text#168]
Hi, 
first and foremost congratulations on the best, in my opinion theme for Intellij IDEA. I love using it as distinguishing different parts of code comes with ease.
There is only one drawback I'd like to address. All generated packages and files in general has a bright orangish background covering files' names (especially Filter Spectrum). It's impossible to see file's name without explicitly marking it. Would be awesome if you could fix it. Please find some screenshot below. I attached also a screenshot from classic Dark theme for comparison purpusoes

![Filter Spectrum](https://github.com/Monokai/monokai-pro-sublime-text/assets/79103766/6918f9e4-2dbc-4e7a-b2df-11de08da0f11)
![Dark](https://github.com/Monokai/monokai-pro-sublime-text/assets/79103766/005739bc-b066-4364-b96c-3cf85eed6b62)

**Comment by Monokai** [comment]
This is the repository for Monokai Pro for Sublime Text. The package for IntelliJ is not an official Monokai Pro theme.
