### ISSUE TITLE
Add YAML file type icon

### ISSUE THREAD

**Issue by ntwb** [Monokai/monokai-pro-sublime-text#17]
It would be awesome if an icon for the YAML file type supporting both `.yml` and `.yaml` extensions were added please

**Comment by Monokai** [comment]
Added in 1.0.4

**Comment by ntwb** [comment]
Thanks a bunch @Monokai 💐 

How do we upgrade to 1.0.4? I've currently got 1.0.3 installed which was the version available when I purchased the Pro license.

I've tried CMD+SHIFT+P -. PACKAGE CONTROL: Upgrade Package and no upgrade to 1.0.4 is shown, I've also restarted ST3 and tried that again to no avail.

So as you've added it 1.0.4 I guess I should ask if 1.0.4 has been released?

**Comment by Monokai** [comment]
Something went wrong so that Package Control couldn't see my update. Should catch up automatically later today.

**Comment by ntwb** [comment]
Cheers 👍
