### ISSUE TITLE
Please support PlainTasks

### ISSUE THREAD

**Issue by dahanbn** [Monokai/monokai-pro-sublime-text#21]
Hello,

I truly like and used some Monokai variants on editors that I use (Emacs, Vim, SublimeText) and I somehow love that theme. The new pro style is awesome as well.

I also manage my todos in plain text and was wondering if you could also create a color scheme for PlainTasks (https://github.com/aziz/PlainTasks) and also create nice todo icons. 

That would great, because there isn't a Monokai theme for plain tasks yet.

Would love to see it.

**Comment by Monokai** [comment]
This does involve quite some work. I'll investigate later.

**Comment by dahanbn** [comment]
That would be totally great and appreciated. 👍

**Comment by Monokai** [comment]
I can't find the time for this at the moment. Closing for now.
