### ISSUE TITLE
Bold and italics support in restructuredText (plus icons)

### ISSUE THREAD

**Issue by dahanbn** [Monokai/monokai-pro-sublime-text#22]
Besides programming is Markdown and restructuredText heavily used by bloggers / writers.  Therefore it would be nice to have both fully supported from the theme.

The main syntax highlighting of restructuredText works with Monokai Pro. But bold and italics aren't highlighted in same way than in Markdown. Maybe you can change that. 

Also a custom icon for restructeredText would be really awesome.

**Comment by Monokai** [comment]
Icon + syntax highlighting added in 1.1.0

**Comment by dahanbn** [comment]
Thanks. 

Unfortunately, I don't get it to work. I use the [RestructuredText Improved](https://packagecontrol.io/packages/RestructuredText%20Improved) and don't see any differences. I also looked in the icon folder and don't see the icons for it.  I checked and I already have 1.1.0 installed.

**Comment by Monokai** [comment]
What happens when you re-select "Monokai Pro" as your theme?

**Comment by dahanbn** [comment]
Highlighting works now - with the Pro theme and with all filters beside Ristretto. I am not able to switch back to Ristretto in RST.

Icon is still missing.

**Comment by Monokai** [comment]
I don't understand the Ristretto thing, that is really weird and I cannot replicate that. If you have any more insights into this, I'm all ears.

Regarding the icon: I think that might be #25

**Comment by dahanbn** [comment]
I checked if I already have removed other themes. After removing Cobalt 2 I got file icons for .json and sublime-menu in the sidebar. They were missing too. And after a restart of ST 3 Build  3142 I am able to select Ristretto (and all other filters) again. 

Icon is still missing for .rst though.

**Comment by dahanbn** [comment]
Whatever changed now. RST icon are used in my sidebar now. Strange. Now it is closed. Sorry to have bothered you. It works fine.

Thank you for the quick support and that you took your time to add those things. Means a lot to me.
