### ISSUE TITLE
"Find In Files..." UI clipped at bottom

### ISSUE THREAD

**Issue by jdhartley** [Monokai/monokai-pro-sublime-text#24]
In Sublime Text 3 on Mac OS X using Monokai Pro, the "Find > Find in Files..." (⇧⌘F) UI is cut off on the bottom, hiding most of the "Replace" line. You can still type in the field and click the Replace button, you just can't see what you are typing!

## Monokai Pro
![image](https://user-images.githubusercontent.com/405538/29724063-f4f0f202-897b-11e7-8e2e-09e474982c48.png)

## Default
![image](https://user-images.githubusercontent.com/405538/29724072-f7ce143c-897b-11e7-8ef7-26ec7b2b6249.png)

## `Preferences.sublime-settings`
```json
{
    "auto_complete_delay": 0,
    "color_scheme": "Packages/Theme - Monokai Pro/Monokai Pro (Filter Spectrum).tmTheme",
    "copy_with_empty_selection": false,
    "ensure_newline_at_eof_on_save": true,
    "font_size": 15,
    "highlight_modified_tabs": true,
    "keymaps":
    {
        "show_pretty_keys": true
    },
    "monokai_pro_minimal": true,
    "monokai_pro_small_scrollbar": true,
    "scroll_past_end": true,
    "shift_tab_unindent": true,
    "theme": "Monokai Pro (Filter Spectrum).sublime-theme",
    "translate_tabs_to_spaces": true,
    "trim_trailing_white_space_on_save": true,
    "word_wrap": true
}
```

**Comment by Monokai** [comment]
Yes, this is an annoying bug. Sublime Text doesn't correctly auto-resize that panel when you switch themes. You can grab the top part of that panel and slowly drag it up. Then you can grab it again and drag it down until you cannot go smaller. Sublime Text remembers your setting.

**Comment by jdhartley** [comment]
Thank you! That fixed it up perfectly. Appreciate it!
