### ISSUE TITLE
Some icons aren't showing

### ISSUE THREAD

**Issue by carlevison** [Monokai/monokai-pro-sublime-text#25]
<img width="137" alt="screen shot 2017-08-29 at 12 36 43" src="https://user-images.githubusercontent.com/6619631/29819053-da3ae36c-8cb6-11e7-903e-3a0ad347fe94.png">

**Environment**

- Operating system and version:
     - [x] Mac OS 10.12.6
- Sublime Text:
    - [x] Dev Build 3142
- Monokai Pro Theme release:
    - [x] v1.0.4

**Comment by Monokai** [comment]
This happens when you have multiple themes installed and they have conflicting file icon definitions. Sublime Text aggregates all file icon definitions, even if your theme is not active. So, one option is to remove the themes you don't need.

**Comment by carlevison** [comment]
<img width="155" alt="screen shot 2017-08-30 at 17 52 41" src="https://user-images.githubusercontent.com/6619631/29884675-13867668-8dac-11e7-8470-54ca15943b7d.png">

You're right as soon as I deleted my themes the file icon came back. Although the html icon is using the same icon as xml.

Any ideas?

**Comment by Monokai** [comment]
I don't have a separate icon for html for now, maybe later :)

**Comment by carlevison** [comment]
That would be great 👍 

closing as issue has been fixed.
