### ISSUE TITLE
Make sidebar icons larger

### ISSUE THREAD

**Issue by imdadahad** [Monokai/monokai-pro-sublime-text#27]
It would be nice to control the size of sidebar icons and text. It's pretty small and isn't very accessible.

**Comment by carlevison** [comment]
This is already available.

monokai_pro_sidebar_font_size
overrides the standard font size of the sidebar (default 12)

**Comment by Monokai** [comment]
The icons are specifically optimized for 16x16px though and they won't scale along. The thing is that these images become blurry when you scale them in arbitrary sizes. So if you want super crisp icons, you need to create them for a specific size and perfectly line up the pixels. I found that 16x16px is a nice balance between recognizability and the number of files you can fit in the sidebar.
