### ISSUE TITLE
Comments and Brackets are the same...

### ISSUE THREAD

**Issue by hozza** [Monokai/monokai-pro-sublime-text#28]
when using the 'Pro' variant of the colour scheme, it seems as if the comments and brackets (for fucntions, arrays etc in PHP) are the same colour if not very close...?

I like the idea of brackets being a darker colour to focus on the other data and controls but being the same as comments is a tad confusing IMO.

**Comment by Monokai** [comment]
Can you please explain why you find it confusing? I cannot think of a scenario where comments and brackets are perceived as being the same.

It was a deliberate decision to tone down punctuation and comments. Both for the same reason actually: to focus on the most important things in your code.

**Comment by hozza** [comment]
I completely agree with the toning down of the brackets idea, makes it much clearer when drilling down into arrays/objects etc.

Specifically came across a document that had an inline comment within a set of brackets - although not normal - brackets and comments have such distinct differences that I thought even if not a common occurrence they would be better being slightly different colors although still toned down to represent how completely different their meanings are.

But all in all, 10/10 would use syntax highlighting again :+1:
