### ISSUE TITLE
Creating new file in directory hide the panel beneath status bar even status bar is off.

### ISSUE THREAD

**Issue by CoffeeQuotes** [Monokai/monokai-pro-sublime-text#29]
Whenever, I try to create new file in directory form sidebar the panel that's popup for the file name is stuck inside, and I could not see the name of the file I am going to create.
[Here you can see](https://imgur.com/acKnAxE)

**Comment by Monokai** [comment]
Yes, this is a known bug with Sublime. See [this comment](https://github.com/Monokai/monokai-pro-sublime-text/issues/24#issuecomment-326039170) to fix it.
