### ISSUE TITLE
[osx] Integrated titlebar

### ISSUE THREAD

**Issue by AlexKvazos** [Monokai/monokai-pro-sublime-text#3]
Are there plans to have the titlebar of the UI theme be integrated?

The "Adaptive" UI Theme is a great example of this.
<img width="997" alt="screen shot 2017-06-13 at 4 52 04 pm" src="https://user-images.githubusercontent.com/4448627/27106353-b0b23102-5058-11e7-9470-c003b9e2c877.png">

**Comment by Monokai** [comment]
I'm not sure. I like consistency across my OS and I remember I tried it before and wasn't satisfied with the result.

Will give it another try later.

**Comment by AlexKvazos** [comment]
Please do! Perhaps you could make it a settings option for those that prefer the system default.
This is all I am missing to finish loving the theme and purchase it 😄.

**Comment by AlexKvazos** [comment]
Hi @Monokai, any chance this will be a coming feature?

**Comment by AlexKvazos** [comment]
@Monokai Hey there! Really just waiting for this issue to finally purchase. Loving Monokai pro; Just needs this.

**Comment by Monokai** [comment]
1.1.0 has a new option: `monokai_pro_style_title_bar`. Set to `true` for integrated title bar in Sublime Text Dev Channel.

**Comment by AlexKvazos** [comment]
Thank you! Just purchased <3
