### ISSUE TITLE
Higher contrast color scheme options or fully monochrome UI

### ISSUE THREAD

**Issue by matrushka** [Monokai/monokai-pro-sublime-text#30]
Is it possible to have an higher contrast (slightly darker background and slightly brighter text such as https://github.com/sprngr/spacegray-monokai op https://github.com/s10wen/Monokai-Phoenix) color scheme options or a setting for a fully monochrome UI so I can use it with any color scheme without having mismatching colors?

**Comment by Monokai** [comment]
Actually Monokai Pro (Filter Spectrum) has a slightly higher contrast than the default Monokai Pro.
