### ISSUE TITLE
Is "Markdown: linebreak"  syntax highlighting supported?

### ISSUE THREAD

**Issue by dahanbn** [Monokai/monokai-pro-sublime-text#31]
Sometimes I use the Markdown: linebreak syntax (two blank spaces) at the end of a line to specify a linebreak. 

I didn't get a special syntax highlight for that with your color schemes. Do I have to enable something to get that behaviour?

**Comment by Monokai** [comment]
I'm depending on syntax definition packages for my syntax highlighting. I'm afraid this cannot be solved in the syntax highlighting, as the necessary scopes are probably just not recognized by the syntax definition package. At least with my Markdown package I don't see any special scopes when I type two spaces at the end of a line (you can check this via the ScopeHunter package).

**Comment by dahanbn** [comment]
There is a similar issue for Markdown Editing.

https://github.com/SublimeText-Markdown/MarkdownEditing/issues/408

Maybe that helps.

**Comment by dahanbn** [comment]
I also asked in the Sublime Text forums and I got the following answer that  line breaks are defined as punctuation.definition.hard-line-break.markdown in the default Markdown syntax which is shipped with Sublime Text 3.

Here the link to the forum entry which also contains a link to the Markdown.syntax definition.

https://forum.sublimetext.com/t/how-to-get-markdown-linebreak-support-syntax-colour-scheme/32171

**Comment by Monokai** [comment]
Added in 1.1.2. Sublime Text doesn't support underlines, so I needed to set the background of those characters.
