### ISSUE TITLE
prepurchase: how many computers can i use the license on ?

### ISSUE THREAD

**Issue by niladam** [Monokai/monokai-pro-sublime-text#32]
Hello,

I'm thinking about purchasing your package. How many computers am i allowed to run it on ?

Thanks.

**Comment by niladam** [comment]
@Monokai hello ? It's been 3 days since i've had a question. Can you please answer this ?

Thanks.

**Comment by dahanbn** [comment]
I am not @Monokai, but I already purchased. For me it works on as many installations as I like. I see it similar to the Sublime Text license. It's a personal license and you might use it on all your personal installations.

**Comment by Monokai** [comment]
You may use one license for one editor on all your personal computers.
