### ISSUE TITLE
Class names color on vscode

### ISSUE THREAD

**Issue by skyline0717** [Monokai/monokai-pro-sublime-text#35]
I think they were supposed to be green like in Sublime Text.
![capture](https://user-images.githubusercontent.com/26013661/30856899-264bef3a-a2ba-11e7-9ff0-9df7440c40a1.PNG)

**Comment by Monokai** [comment]
vscode doesn't have the same scope definitions as sublime, and vscode lacks these specific class scopes for html attributes.
