### ISSUE TITLE
"Goto symbol in project" is too small

### ISSUE THREAD

**Issue by hanoii** [Monokai/monokai-pro-sublime-text#37]
I'd like to have the "Goto symbol in project

<img width="284" alt="screen shot 2017-10-03 at 11 42 41 pm" src="https://user-images.githubusercontent.com/677879/31157917-9b3fe140-a894-11e7-9ca7-d325766610d9.png">

A lot bigger, and maybe configurable, but really wider is almost a must:

<img width="394" alt="screen shot 2017-10-03 at 11 41 56 pm" src="https://user-images.githubusercontent.com/677879/31157924-a5ff864e-a894-11e7-926d-41711a62dc9f.png">

**Comment by Monokai** [comment]
I'm afraid I cannot change the width of this panel. This is how Sublime Text itself decides to display it.

**Comment by hanoii** [comment]
But it looks a lot wider with a different theme in the same project
