### ISSUE TITLE
Command Palette width

### ISSUE THREAD

**Issue by jbwilhite** [Monokai/monokai-pro-sublime-text#38]
I really like this theme but I've found it makes the Command Palette (Cmd+Shift+P) too narrow to read long items text.

Though, In your example screenshots it appears much wider, so there might just be an issue with my setup.

Monokai Pro Theme
![image](https://user-images.githubusercontent.com/6500087/31184882-9aa37fd0-a8f8-11e7-83d8-3cf41d2244b5.png)

Default Sublime Theme
![image](https://user-images.githubusercontent.com/6500087/31184977-d6d533cc-a8f8-11e7-9608-7d0b9b7b2922.png)

Any suggestions? Thanks!

**Comment by Monokai** [comment]
I see this too. Unfortunately, I cannot define the width of the command palette as Sublime Text handles this internally. I have the feeling that Sublime Text miscalculates the width if a non-standard font family is set. If that's true, either that needs to be fixed or I need to provide an option to not override the font family on these panels.

**Comment by Monokai** [comment]
Fixed in Sublime Text build 3155
