### ISSUE TITLE
Syntax Highlighting in 1.1.2

### ISSUE THREAD

**Issue by ivansvlv** [Monokai/monokai-pro-sublime-text#39]
Hi there! First of all I really appreciate all the work you do with Monokai Pro, thank you.

With the latest update I've seen changes in the syntax highlighting while working with Puppet manifest. So before bombarding with screenshots etc., just wanted to figure out if you've changed something.

P.S. Talking about Sublime Text 3.

**Comment by Monokai** [comment]
I didn't explicitly change something for Puppet manifest, I don't even know what is is :) The syntax highlighting changes from 1.1.1 to 1.1.2 were minimal. Are you able to post screenshots and explain what's different? Maybe I can have a look.

**Comment by ivansvlv** [comment]
Hi!

"I didn't explicitly change something for Puppet manifest, I don't even know what is is :)" - yea, I didn't mean that :) just it happened that I was working with Puppet manifest when syntax highlighting changed.

As for the screenshots, here they are

Monokai Pro:
<img width="338" alt="monokai_pro" src="https://user-images.githubusercontent.com/16175855/31219530-4afa1628-a9c6-11e7-8f10-bb401f1e6197.png">

Monokai (default ST3):
<img width="326" alt="monokai_default" src="https://user-images.githubusercontent.com/16175855/31219562-63ccbeb2-a9c6-11e7-9726-893f00f40fd4.png">

Monokai Pro used to highlight those "properties" of the vhost, the same way as Monokai (default) with purple color but in Pro color palette, now they are just white.

**Comment by ivansvlv** [comment]
Ok, it changed even more after the release of ST Build 3146 (they've announced some syntax changes too):

Monokai Pro:
<img width="272" alt="monokai_pro build3146" src="https://user-images.githubusercontent.com/16175855/31263846-a29c0f74-aa6d-11e7-81e1-d3042f67819f.png">

Monokai Default:
<img width="260" alt="monokai_default build3146" src="https://user-images.githubusercontent.com/16175855/31263847-ac04ccb8-aa6d-11e7-9377-ae52acaab993.png">

Arrows became grey, in larger files bigger portion of syntax is greyed out like in this example apache vhost config:

<img width="481" alt="vhost_monokai_pro" src="https://user-images.githubusercontent.com/16175855/31263981-9ae5470e-aa6e-11e7-9359-e1c5e07a72a7.png">


Hope this is somewhat helpful.

**Comment by gobijan** [comment]
Came here to report the same thing. Since Build 3146 normal text has the dark color used for comments...

**Comment by Monokai** [comment]
The new dev build changed how default text color is rendered. Fixed this in 1.1.3 by setting default colors in the `text` and `source` scopes. Additionally, I fixed the color of the constants in the Puppet language.

**Comment by ivansvlv** [comment]
And instantly everything looks awesome again! Thank you very much!

**Comment by gobijan** [comment]
:)

**Comment by giltig** [comment]
Hi,
I'm with the latest build version of sublime and the font in the search area (bottom menu) is gray and not white although I remove the package and reinstalled it 
![image](https://user-images.githubusercontent.com/5754742/33527266-67ffdb54-d856-11e7-9f98-5ccd8fdfb186.png)
