### ISSUE TITLE
Ruby Syntax is broken in latest ST 3147 Dev Build.

### ISSUE THREAD

**Issue by gobijan** [Monokai/monokai-pro-sublime-text#40]
Unfortunately Ruby Syntax is broken since the changes to themes in 3147.
See screenshot:

<img width="958" alt="bildschirmfoto 2017-10-06 um 20 03 16" src="https://user-images.githubusercontent.com/49339/31291934-c393c3a2-aad1-11e7-992d-72ddf70bd7af.png">

**Comment by Monokai** [comment]
The new dev build changed how default text color is rendered. Fixed this in 1.1.3 by setting default colors in the `text` and `source` scopes.

**Comment by gobijan** [comment]
Oh nice so when will 1.1.3 be available? :)

**Comment by Monokai** [comment]
PackageControl just picked it up: https://packagecontrol.io/packages/Theme%20-%20Monokai%20Pro

So any time you either restart SublimeText or manually update the theme via `PackageControl > Upgrade Package`

**Comment by gobijan** [comment]
Great! THX
