### ISSUE TITLE
The support for Golang is unsatisfactory ...

### ISSUE THREAD

**Issue by wy-z** [Monokai/monokai-pro-sublime-text#41]
![image](https://user-images.githubusercontent.com/4213483/31315037-7af90fea-abd4-11e7-8803-638d39d8aef9.png)

**Comment by Monokai** [comment]
Seems like you've been hit by the changes in the new dev-build. Please update Monokai Pro to 1.1.3 and that will solve the grayed-out text.

**Comment by wy-z** [comment]
Good~3Q
