### ISSUE TITLE
Fonts in Sublime Text

### ISSUE THREAD

**Issue by desislavsd** [Monokai/monokai-pro-sublime-text#48]
I have tried the theme in Sublime Text ( Windows ), but seems some of the fonts that I see on the screenshots do not match the ones I see in the editor. I really like the one used for the keywords like `const` and `function`, but my Sublime uses default italic font. Am I missing something? 

Thanks in advance!

**Comment by ivansvlv** [comment]
Hi there! Yup, you are missing a $200 font :) https://www.typography.com/fonts/operator/styles
