### ISSUE TITLE
Syntax highlighting seems flawed for Ruby.

### ISSUE THREAD

**Issue by gobijan** [Monokai/monokai-pro-sublime-text#49]
First of all: I love this Theme and use it daily in VSCode. The sublime version looks even better but for me syntax highlighting seems to be out of date and for example ruby highlighting doesn't use all the features like the default theme (Mariana) does.

Here is a screenshot that shows that the symbols and hashes are not highlighted:
<img width="574" alt="bildschirmfoto 2017-11-01 um 06 23 57" src="https://user-images.githubusercontent.com/49339/32261230-6e58efce-becd-11e7-9b28-489798e4ba21.png">
<img width="524" alt="bildschirmfoto 2017-11-01 um 06 24 27" src="https://user-images.githubusercontent.com/49339/32261234-72255de0-becd-11e7-88a7-9b2b37a6ce86.png">

**Comment by emigdio821** [comment]
Hello, could you please tell me which font are you using mate? Thanks.

**Comment by gobijan** [comment]
Sure this is “SF Mono” on a Mac (the default font Xcode uses btw)

**Comment by Monokai** [comment]
added better ruby highlighting in 1.1.5

**Comment by gobijan** [comment]
Awesome! Just bought a license for Sublime, too (already have VSCode) :)
