### ISSUE TITLE
Math Preview in LaTexTools shows strange prefix

### ISSUE THREAD

**Issue by hsiktas** [Monokai/monokai-pro-sublime-text#50]
This is how it looks with the default theme:
![image](https://user-images.githubusercontent.com/4571159/32353310-2d2d69ea-c025-11e7-955e-5700aec5e6f9.png)
With Monokai Pro it looks like this:
![image](https://user-images.githubusercontent.com/4571159/32353349-53fe0e8a-c025-11e7-9046-c3978c1f19f4.png)

For some reason I get this black "3F" at the beginning of each inline math expression.
It works fine with other themes but for some reason I am seeing this issue with Monokai Pro.

**Comment by Monokai** [comment]
fixed in 1.1.5

**Comment by hsiktas** [comment]
Thanks, it works now! And my license is purchased. :)
