### ISSUE TITLE
Sublime settings not being applied

### ISSUE THREAD

**Issue by emigdio821** [Monokai/monokai-pro-sublime-text#51]
Hi, first of all, thanks for this awesome theme.
I was trying to use the setting you mention on the web page, and seems that those settings are not working for me, what am I doing wrong? Thanks in advance.

![image](https://user-images.githubusercontent.com/6751108/32386248-85d9bb2a-c08e-11e7-9f13-86d7300524a7.png)

**Comment by ivansvlv** [comment]
try to move those settings (except license key and email) to your general ST settings. Right now I'm completely default in context of Monokai Pro, but previously i guess when i was tweaking it, i did it in general settings. not sure though

**Comment by emigdio821** [comment]
It worked perfectly, thanks a lot mate :)

**Comment by ivansvlv** [comment]
you are welcome :)
