### ISSUE TITLE
Command palette looks broken in Sublime Text build 3154

### ISSUE THREAD

**Issue by frankrausch** [Monokai/monokai-pro-sublime-text#53]
<img width="802" alt="monokai-pro-st3154" src="https://user-images.githubusercontent.com/6783714/32689304-27117bdc-c6e2-11e7-9073-a9cbdeb0ad31.png">

**Comment by django-wong** [comment]
+1

**Comment by gobijan** [comment]
Latest Sublime Dev Build (3155) fixed command palette ui problems. Voting to close the issue as it was probably more on Sublime Side than on Monokai Pro.

**Comment by Monokai** [comment]
Closing this, was indeed a bug with SublimeText.
