### ISSUE TITLE
LESS files seems unsupported

### ISSUE THREAD

**Issue by yomzed** [Monokai/monokai-pro-sublime-text#56]
![selection_081](https://user-images.githubusercontent.com/24735012/33932827-50e980c8-dff4-11e7-9583-0a438a2f7303.png)

I was testing Monokai Pro on different type of files and LESS ones seems to break the syntax colors. Am I missing a setting or is it a bug?

Thanks

Monokai Pro 1.1.4
Sublime Text 3 Build 3143

**Comment by Monokai** [comment]
Syntax highlighting is a dance between syntax definitions and color schemes. I think I saw a message that the LESS package for syntax definitions had been updated. I'm testing it now with the Monokai Pro color scheme and it looks like it works. Can you please confirm?

**Comment by yomzed** [comment]
Everything seems fixed for me too! 
Thanks :)
