### ISSUE TITLE
Permission to use your theme in Jetbrains

### ISSUE THREAD

**Issue by mallowigi** [Monokai/monokai-pro-sublime-text#57]
Hi, I'm getting in touch with you to know if you're interested on porting your theme to my plugin (https://github.com/ChrisRM/material-theme-jetbrains). My plugin allows users to customize the appearance of the Jetbrains IDEs and I've included a set of themes.

I was wondering if you were interested on letting me include your theme in the list of themes? I know your theme is not free so I'm asking you if you're interested either way. In this case I'll include your name in the authors, of course, and a Paypal/Flattr/Gratipay link if you'd like. Your work on the theme is impressive and it would be a shame for IntelliJ users to not be able to profit from it.

As for what I'm including in the theme, currently I'm only interested in the Pro flavor, and I'm not interested in the icons, font or padding since there is no way currently in my plugin to change them on a per-theme basis.

So WDYT?

**Comment by Monokai** [comment]
I'm having some trouble finding time to implement Monokai Pro for other editors, but support for Jetbrains is on my list.

**Comment by calvinanderson** [comment]
@Monokai 

+1 for this.  I purchased your theme for VSCode but I spend half my time in JetBrains IDEs for PHP, so this would be great.

**Comment by mmohamedali** [comment]
@Monokai a lot of developers use Jetbrains IDE's whether it's IntelliJ, CLion, PyCharm, and many others. So, I'd be glad to see your theme implemented there.

**Comment by Gameghostify** [comment]
Any updates about this? With the official support for themes added to IntelliJ, I'd love to have Monokai Pro added to it!

**Comment by mallowigi** [comment]
There are already some themes for Monokai Pro

**Comment by Gameghostify** [comment]
That's correct, however every one of them I've tried is using some other set of colors/highlights some keywords differently (e.g. `const` in JavaScript is hot-pink in IntelliJ/WebStorm while its light-blue and slanted/italicized in VSCode). Additionally, these themes aren't supported by @Monokai 🙁 

I think having the official version of Monokai Pro in JetBrain's product suite would be awesome 👍

**Comment by dolpsdw** [comment]
> I'm having some trouble finding time to implement Monokai Pro for other editors, but support for Jetbrains is on my list.

Hi, with the new 2019 jetbrains themes it is fairly simple to make this.
Checkout https://github.com/bmikaili/intellij-monocai-theme

**Comment by Gameghostify** [comment]
@Monokai any updates on this? All the themes in the IntelliJ store aren't official (some even impersonate) and aren't exactly like the original Monokai Pro (small details are different, and there are no filters)

**Comment by jontaydev** [comment]
@Monokai I would love to see official support for JetBrains as well. The material theme from @mallowigi is passable, but has odd differences with the official sublime/vscode theme, and it doesn't support filters. Plus, the material plugin is quite a bit bloated for my liking.

**Comment by mallowigi** [comment]
Ummm... yes, you're right about the plugin being bloated and not having filters (they are in the premium support anyway) but what differences do they have? can you point me to some examples?

**Comment by jontaydev** [comment]
@mallowigi It's minor, but the syntax coloring looks just a little different:

<img width="994" alt="Screen Shot 2019-12-08 at 4 54 18 PM" src="https://user-images.githubusercontent.com/2243530/70396967-d9278700-19db-11ea-862d-af12e3930b3d.png">
<img width="1070" alt="Screen Shot 2019-12-08 at 4 54 09 PM" src="https://user-images.githubusercontent.com/2243530/70396968-d9278700-19db-11ea-8c50-82c040995c97.png">

By the way, I discovered the Material Lite plugin, and its pretty great. Thanks!

**Comment by mallowigi** [comment]
This looks like a difference in how Visual Studio colors the editor rather than actual differences. I can guarantee that you won’t be able to reproduce the same behavior between VSC and IJ.

**Comment by Monokai** [comment]
Psst: https://monokai.pro/jetbrains

**Comment by mallowigi** [comment]
Congrats Wimer! There were already non-official versions of the theme but I'm happy you finally did it!
