### ISSUE TITLE
Possible to download without Package Control?

### ISSUE THREAD

**Issue by ianlawson1234** [Monokai/monokai-pro-sublime-text#60]
Due to the nature of my job, my sublime doesn't have access to the world wide web.

Is there a way to obtain a zip of the latest build?

Cheers!

**Comment by mgussekloo** [comment]
Maybe you could try downloading the latest release-URL from here: https://packages.monokai.pro/packages.json

Download the .package, add .zip, and unzip to your local /Packages/User/Theme - Monokai Pro/

Don't know if it works, but it might.
