### ISSUE TITLE
Tab title of temporary tabs is cut off

### ISSUE THREAD

**Issue by hsiktas** [Monokai/monokai-pro-sublime-text#61]
The file name in the tab title is cut off a little if that tab still temporary (single click in sidebar instead of double click; italic font).

Here is a temporary tab: 
![image](https://user-images.githubusercontent.com/4571159/34923863-d7c1db80-f99f-11e7-88d1-661c67d0e457.png)
And here the same tab but permanent: 
![image](https://user-images.githubusercontent.com/4571159/34923877-f58e8dca-f99f-11e7-86b7-b13f427f97a6.png)

Note that the 'x' is cut off a little in the first screenshot. This does also happen with the default font for this theme.

**Comment by Monokai** [comment]
I cannot reproduce this. Maybe this is a Sublime Text bug?

**Comment by hsiktas** [comment]
Just checked it again: I still can see this issue on Windows but not on macOS. Maybe only Windows is affected?

**Comment by Monokai** [comment]
I suspect it's a bug with Sublime. Closing for now.
