### ISSUE TITLE
How to change the sidebar font with new license

### ISSUE THREAD

**Issue by robbyki** [Monokai/monokai-pro-sublime-text#66]
Is there a reference somewhere that shows how to exactly apply the sidebar font size customization? I just purchased the license but can't figure out how to add it the settings.

**Comment by ntwb** [comment]
Click the "Show Settings" link on this page https://www.monokai.pro/sublime-text/

**Comment by robbyki** [comment]
Thank you. I do see the below note `monokai_pro_sidebar_font_size` but I'm pretty new to sublime and I already tried adding the following to the `Theme - Monokai Pro.sublime-settings` file with no luck. How should I be adding that line? 

```
{
        "monokai_pro_sidebar_font_size": 16
}
```

**Comment by robbyki** [comment]
Thanks. Was adding the line in the wrong settings file.
