### ISSUE TITLE
Proposal of a new color variant - flat

### ISSUE THREAD

**Issue by rofrol** [Monokai/monokai-pro-sublime-text#67]
Similar to Material Design that sidebar has the same background color as  editor.

Also white text is more dimmed: `#BEC4CB`.

And for `fontStyle`: `italic` changed to `normal`.

```json
{
      "[Monokai Pro]": {
          "sideBar.background": "#2D2A2E",
          "sideBar.border": "#2D2A2E",
          "panel.background": "#2D2A2E",
          "terminal.background": "#2D2A2E",
          "statusBar.background": "#2D2A2E",
          "statusBar.border": "#2D2A2E",
          "sideBarSectionHeader.background": "#29262A",
      },
}
```

<img width="1680" alt="screen shot 2018-02-14 at 11 34 07 am" src="https://user-images.githubusercontent.com/28787/36199899-42f49a12-117b-11e8-9bc9-5f41fea18f67.png">

**Comment by emigdio821** [comment]
How do you set those colors? Looks nice, this would be nice to implement.

**Comment by rofrol** [comment]
In the user settings.

**Comment by gobijan** [comment]
Seems like you are referencing to the vscode version of monokai.pro. The sublime version of monokai pro has a minimal setting that unifies sidebar and editor.

**Comment by Monokai** [comment]
This is the Sublime issue repo :) Here's the [issue repo for VSCode.](https://github.com/Monokai/monokai-pro-vscode). Looks nice though. I'll see if I can replicate the setting of Sublime for VSCode in a next update.
