### ISSUE TITLE
The 'invalid' scope should be more obvious

### ISSUE THREAD

**Issue by TheIronBorn** [Monokai/monokai-pro-sublime-text#68]
Currently it seems `invalid` only makes the text italic and doesn't change colors at all.  

Most color schemes do something like: ![screen shot 2018-03-08 at 10 53 06](https://user-images.githubusercontent.com/7707250/37170532-f4323b66-2302-11e8-9e42-0d4107dcd9eb.png) (red background, bright foreground) and I feel something closer to that would be useful.

**Comment by s-clerc** [comment]
I’d prefer yellow and black, but I strongly agree.

**Comment by kevinsjoberg** [comment]
@Monokai would you mind taking a stab at this? Here's a concrete example:

Open a new document, set the syntax to `Ocaml` and enter the next `123xyz`.

Using the default color scheme, `Mariana`, this is what we see:

<img width="207" alt="Screenshot 2022-03-24 at 09 39 53" src="https://user-images.githubusercontent.com/503025/159876310-61a1fd9d-c8d8-44d4-b0c3-7c53f3d07a12.png">

Using any Monokai Pro color scheme, this is what we see:

<img width="207" alt="Screenshot 2022-03-24 at 09 41 44" src="https://user-images.githubusercontent.com/503025/159876629-842ecd3b-d484-4918-91dd-4ca2ee14ce34.png">

The scope being used here is `invalid.illegal.numeric.ocaml` and I assume we want to add styling for `invalid` and `invalid.deprecated` as these are being defined by `Mariana`. See the snippet below:

```json
{
  "name": "Invalid",
  "scope": "invalid",
  "foreground": "var(white2)",
  "background": "var(red)"
},
{
  "name": "Invalid deprecated",
  "scope": "invalid.deprecated",
  "foreground": "var(white2)",
  "background": "var(orange2)"
}
```

**Comment by kevinsjoberg** [comment]
In the meantime, anyone could customize the theme themselves to get around this by taking the following steps.

Open the Command Palette and select "UI: Customize Color Scheme". Under the `rules` property, add the following rules:

```json
{
	"name": "Invalid",
	"scope": "invalid",
	"foreground": "var(white)",
	"background": "var(red)"
},
{
	"name": "Invalid deprecated",
	"scope": "invalid.deprecated",
	"foreground": "var(white)",
	"background": "var(blue)"
}
```

**Comment by Monokai** [comment]
I've adjusted this in 1.1.21. I didn't adjust the background though, because I found that while you're typing, the partly typed code is often invalid, so you would have a lot of visual flickering.

I agree though that more prominent colors for invalid code are easier to spot when you quickly scroll through your code. So I think a red foreground color with an underline is a good compromise here.
