### ISSUE TITLE
Support the Oni editor

### ISSUE THREAD

**Issue by bfulop** [Monokai/monokai-pro-sublime-text#69]
Hello,

I love your theme and was my choice for using Sublime but very recently I switched to [Oni Vim](https://github.com/onivim/oni). It's a fantastic, open-source editor, worth checking out!

I got so much used to your colour scheme that, I cannot code without it now! So I just pasted some of your colours into the Vim Monokai theme to approximate the Monokai Pro theme.

Now, my question is, are you OK with me sharing this colour scheme with other Oni users? Would you be willing to consider porting your theme to this editor?

Thank you,

Balint

**Comment by Monokai** [comment]
Supporting Sublime and VSCode is the most I can do at the moment, even if I wish to support all editors in the world :)
