### ISSUE TITLE
Display sidebar_heading

### ISSUE THREAD

**Issue by normallywho** [Monokai/monokai-pro-sublime-text#70]
It looks like the sidebar_heading elements are given a color that matches the background of the sidebar. Can you provide an option to give these a color so the headings are visible? I typically have four groups open along with the file list and having the headings there to differentiate the groups is important. Right now, I am manually modifying the color in the theme file, but I lose those changes any time the theme is updated.

So, just asking for a setting like "display_sidebar_headings": true/false would be a great help.

**Comment by Monokai** [comment]
I've added an option for this in 1.1.14: `monokai_pro_sidebar_headings`
