### ISSUE TITLE
how to edit this style

### ISSUE THREAD

**Issue by z2x** [Monokai/monokai-pro-sublime-text#71]
<img width="396" alt="2018-04-13 2 52 32" src="https://user-images.githubusercontent.com/24654957/38720841-58298eec-3f2a-11e8-9df3-3cb6ce78c0e6.png">

This line is too wide. Can you redesign it? Or you can tell me how to modify it.

**Comment by normallywho** [comment]
After upgrading to ST3 build 3170 I'm seeing the thick borders as well.

**Comment by Monokai** [comment]
Fixed in 1.1.7
