### ISSUE TITLE
Symbol highlight improvement

### ISSUE THREAD

**Issue by phuna** [Monokai/monokai-pro-sublime-text#72]
Hi,
Love your theme, but symbol highlight is a bit "rough" to me, I prefer thinner border as in Boxy theme. Can you please change this? Thank you.
* Monokai pro:
<img width="238" alt="monokai pro" src="https://user-images.githubusercontent.com/1096791/38721683-50dcbf56-3f25-11e8-97d6-f082033b0365.png">

* Boxy theme:
<img width="242" alt="boxy theme" src="https://user-images.githubusercontent.com/1096791/38721690-55c8125e-3f25-11e8-9392-9fada9ee5ab6.png">

**Comment by Monokai** [comment]
Fixed in 1.1.7

**Comment by phuna** [comment]
Thanks for the fix. Maybe it's just me but the latest fix seems a bit too dark so it's difficult to quickly see matching symbols when they're not close to each other. Is there any setting that I can make it brighter? 
<img width="219" alt="screen shot 2018-06-12 at 2 56 02 pm" src="https://user-images.githubusercontent.com/1096791/41277472-890df2ea-6e51-11e8-80c4-33fc3b0f1b19.png">
