### ISSUE TITLE
Sublime Linter preferences

### ISSUE THREAD

**Issue by JeanMertz** [Monokai/monokai-pro-sublime-text#73]
The new preferences seem to not work as expected.

The readme details setting `theme` to `Monokai Pro.gutter-theme`, but that property is not allowed:

> Additional properties are not allowed ('theme' was unexpected)

There _is_ a `gutter_theme` property, but if I set that (and copy the rest of the config from the README), then I end up with an orange/yellow striped block where the gutter icon should show up, indicating it can't find the image as expected.

Here's the full config:

```json
// SublimeLinter Settings - User
{
  "gutter_theme": "Monokai Pro.gutter-theme",
  "styles": [
    {
      "mark_style": "none",
      "priority": 1,
      "scope": "region.orangish",
      "icon": "warning",
      "types": [
        "warning"
      ]
    },
    {
      "mark_style": "none",
      "priority": 1,
      "scope": "region.redish",
      "icon": "error",
      "types": [
        "error"
      ]
    }
  ]
}
```

And the following package versions are installed:

* Sublime Linter: `v4.2.1`
* Monokai Pro: `v1.1.6`

**Comment by Monokai** [comment]
Should be this: `"gutter_theme": "Packages/Theme - Monokai Pro/Monokai Pro.gutter-theme"`

Does that work?

**Comment by JeanMertz** [comment]
Yep, that worked as expected. Thanks 👍
