### ISSUE TITLE
Semantic Highlighting

### ISSUE THREAD

**Issue by ianlawson1234** [Monokai/monokai-pro-sublime-text#76]
Any plans to add [Semantic Highlighting](http://www.sublimetext.com/docs/3/color_schemes.html#hashed_syntax_highlighting) since it was added in Sublime 3170?

**Comment by Monokai** [comment]
I'm open to suggestions, but I was not planning this. I think the current color palette is fine as it is. introducing more hues and shades doesn't add to the overall balance. I think it's better to modularize code than to solve keeping track of variable names by adding more hues.

**Comment by gobijan** [comment]
I patched my monokai pro to support it. 
Create a file in your Packages/User folder named 

> Monokai Pro.sublime-color-scheme

containing the following code:

    {
    "rules":
    [
        {
            "scope": "source - punctuation - keyword",
            "foreground":
            [
                "hsl(150, 100%, 80%)",
                "hsl(250, 100%, 80%)",
            ]
        }
    ]
    }

And voila you you get Semantic Highlighting.

**Comment by ianlawson1234** [comment]
Well that was easy - thank you!
