### ISSUE TITLE
Proposal of syntax highlight for ruby instance/class variables

### ISSUE THREAD

**Issue by ascendbruce** [Monokai/monokai-pro-sublime-text#77]
The instance variable is a big thing in Ruby. We use instance variables in Ruby/Rails a lot. I believe it will be nice if we can highlight the entire variable name so that it's easy to differentiate from method names.

Currently it only highlights the `@` symbol:

![monokai-pro-ruby](https://user-images.githubusercontent.com/356911/40157716-20eb7896-59d3-11e8-8019-6e342eca4db8.png)

After highlighting the entire variable name:

![monokai-pro-ruby-mod](https://user-images.githubusercontent.com/356911/40157715-20b4a582-59d3-11e8-83e7-67bada727665.png)

> example code is from http://guides.rubyonrails.org/getting_started.html#deleting-comments

Here is the modification I made on my local machine:

> I also include the highlighting for class variables, start with two `@`, for example: `@@name`

```
      <dict>
        <key>scope</key>
        <string>source.ruby variable.other.readwrite.instance.ruby, source.ruby variable.other.readwrite.class.ruby</string>
        <key>settings</key>
        <dict>
          <key>foreground</key>
          <string>#c1c0c0</string>
        </dict>
      </dict>
```

It may be even nicer to give it a brighter color, another color for class variables. But I can't find a good one from colors which are currently in use. What do you think?

## My environment

* macOS 10.13.4
* Sublime Text: 3.1.1 build 3176
* Monokai Pro.tmTheme uuid 656cdfc7-c181-528c-83a8-3d49b30e385f

**Comment by Monokai** [comment]
I see. There's not really a good equivalent in other languages and after some thinking I settled on violet. If this turns out to be too much, I'm happy to switch it back to white. I also adjusted dimmed the opening / closing brackets.
