### ISSUE TITLE
Sublime Linter Config Example on Package Control wrong

### ISSUE THREAD

**Issue by tobsn** [Monokai/monokai-pro-sublime-text#80]
https://packagecontrol.io/packages/Theme%20-%20Monokai%20Pro

Sublimelinter example should be gutter_theme not theme.

`"gutter_theme": "Monokai Pro.gutter-theme",`

**Comment by Asuza** [comment]
The _Monokai Pro.gutter-theme_ file doesn't exist for me.

**Comment by Asuza** [comment]
I had to extract the theme package archive from the _Installed Packages_ folder and move it to the _Packages_ folder, which allowed me to update my config to:

```json
    "gutter_theme": "Packages/Theme - Monokai Pro/Monokai Pro.gutter-theme"
```
This works, but that seemed like more trouble than it should have been. I'm trying the theme to see if I want to buy it, and it's already giving me trouble. :disappointed:

**Comment by Monokai** [comment]
You're right. I've updated the readme. @Asuza do you have the latest GitGutter?

**Comment by Asuza** [comment]
Yeah, it should be. I have 1.7.15. It looks like that's their latest stable release.
