### ISSUE TITLE
Bug in Monokai Pro settings

### ISSUE THREAD

**Issue by vinibudd** [Monokai/monokai-pro-sublime-text#81]
I open the default settings and users are empty

This is normal?

Windows 10 Home 1803

![sem titulo](https://user-images.githubusercontent.com/24849260/40816247-3aa333d2-6522-11e8-9cf5-252ee1065bf4.png)

**Comment by sus007** [comment]
Since, those files do not exist at all, both post-installation/pre-installation. Yes, it is normal. :smiley:

**Comment by vinibudd** [comment]
Thx
