### ISSUE TITLE
Blinking highlighting of current match of search string when searching / replacing

### ISSUE THREAD

**Issue by x100ex** [Monokai/monokai-pro-sublime-text#86]
When you press "Find" not often, the highlight of the matching string is practically not visible.

When you press "Find" very often, you can see that at first the highlight is yellow, and then instantly the backlight changes to an almost invisible one, merging with the background.

<details> 
<summary> GIF </summary>

![ezgif-2-e4b691c7e2](https://user-images.githubusercontent.com/1345294/43016823-8d46339c-8c6d-11e8-87df-1a11ccf3f889.gif)

</details>

**Comment by Monokai** [comment]
I cannot replicate this (on Mac). Seems like a bug with Sublime Text itself I think?

**Comment by x100ex** [comment]
Mea culpa. It's buggy "Gremlins" package.
