### ISSUE TITLE
Change font size in SublimeText tab strip

### ISSUE THREAD

**Issue by mgussekloo** [Monokai/monokai-pro-sublime-text#87]
Can we change the font size in the tabs? Default is 12px but I really want to change it to 14px, in order to match the rest of my editor. As far as I can see there's an option to change the font family, but not the font size?

**Comment by jdsimcoe** [comment]
I feel exactly the same as @mgussekloo, it feels off when I can't match the tab font size to the sidebar font size. @Monokai is this something you can enable for us?

**Comment by Monokai** [comment]
You can adjust the font size of the labels via `monokai_pro_label_font_size`
