### ISSUE TITLE
Sublime Text occasionally wrongly prompts for license

### ISSUE THREAD

**Issue by philwo** [Monokai/monokai-pro-sublime-text#88]
Hi,

I'm using Sublime Text 3 (Dev Channel Build 3175) and Monokai Pro 1.1.8 on macOS.

I've entered the license when I initially installed the theme, however I still occasionally get prompts that ask me to buy the theme.

When I open the command palette via Cmd-Shift-P, there is no entry called "Monokai Pro: enter license" (only "Monokai Pro: select theme"), so I can't enter the license again.

Any idea?

Cheers,
Philipp

**Comment by jmdev33376** [comment]
Hi,

You need to go to: 
Sublime Text > Preferences > Packages Settings > Theme - Monokai Pro > Settings - User

and create a json file with your email and license:

{
	"email": "your email",
	"license_key": "your license"
}

finally, save it and that's all.

**Comment by philwo** [comment]
I've tried entering the license manually via Sublime Text > Preferences > Packages Settings > Theme - Monokai Pro > Settings - User:

```json
{
	"email": "my.email@example.com",
	"license_key": "aaaaa-bbbbb-ccccc-ddddd-eeeee"
}
```

However, the dialog still pops up. :(
