### ISSUE TITLE
Option to change default UI fonts

### ISSUE THREAD

**Issue by sayakbiswas** [Monokai/monokai-pro-sublime-text#9]
Currently it uses the default system monospace font for the UI. I like to set the UI fonts to the proportional fonts. Is there any chance there would be an option to customize the UI fonts?

Also, currently the fonts on the tabs have an issue. Notice how the 'j' and the 'g' are not showing up properly in the following screenshot.

![screenshot from 2017-06-23 22-06-08](https://user-images.githubusercontent.com/315187/27504843-334b1b1a-5860-11e7-9bef-2de3446bd00a.png)

**Comment by Monokai** [comment]
You can change the sidebar font, but not the tab font currently. I might revisit that at some point. On www.monokai.pro, all the way at the bottom under "show settings" you can find some settings you can use to tweak Monokai Pro further.

Which font are you using? I'm going to investigate the cut-off descenders.

**Comment by sayakbiswas** [comment]
Thanks, I didn't know about the sidebar font settings, would be great to have the tab settings as well. I am currently using Hack fonts on Ubuntu 16.04.2. Default system size of the Hack fonts is 9pts.

**Comment by pentago** [comment]
Plese allow us to change UI font, that's a must. Not everybody likes the defaults so if you want people to actually pay for something, allow them to use it as they please.

**Comment by Monokai** [comment]
Added a new user setting `monokai_pro_ui_font_face`, which you can set to whatever you want for the UI.

**Comment by akirawinz** [comment]
@Monokai How can i get font that show in https://www.monokai.pro/sublime-text/ . Is it availible people who buy license only ?
