### ISSUE TITLE
Use another color for some LaTeX texts (like Sublime 3 default monokai color schema)

### ISSUE THREAD

**Issue by hadisfr** [Monokai/monokai-pro-sublime-text#90]
In Sublime 3 default _monokai_ color schema, the text inside braces of `\cite`, `\nameref` and some other LaTeX commands are shown in a different color (purple). Could you please add the same feature to _monokai pro_?

#### old (Sublime 3 default _monokai_ color schema)
![image](https://user-images.githubusercontent.com/24562441/44645254-446a6700-a9ec-11e8-823b-2ccac7cc83bf.png)

#### new (_monokai pro_::_spectrum_)
![image](https://user-images.githubusercontent.com/24562441/44645274-51875600-a9ec-11e8-9e70-30af35841e70.png)

**Comment by Monokai** [comment]
fixed in 1.1.9

**Comment by hadisfr** [comment]
Thank you @Monokai !
