### ISSUE TITLE
Monochrome icons appear as dimmed version of the original iconset

### ISSUE THREAD

**Issue by sneakyvince** [Monokai/monokai-pro-sublime-text#91]
Using the monochrome icons option: `monokai_pro_file_icons_monochrome: true` ,

results in the following:

![schermafbeelding 2018-09-10 om 23 52 18](https://user-images.githubusercontent.com/10743051/45326717-fe1d1800-b554-11e8-882f-81d6d03d4907.png)

Clearly it's still using the default iconset only this time slightly dimmed, not at all looking like VSCode's monochrome icons.

**Comment by gobijan** [comment]
I have the same effect.

**Comment by Monokai** [comment]
Somehow Sublime Text caches icons I think. Anyway, you have to restart Sublime to see the monochrome icons correctly.

**Comment by Monokai** [comment]
I cannot replicate it. Which platform are you on? And which version of sublime?

**Comment by gobijan** [comment]
I have the same issue on latest sublime dev build and MacOS. I need to say that I have „A file icon“ additionally installed

**Comment by Monokai** [comment]
Still can't replicate it. I know that in the past Sublime Text couldn't work well with multiple (icon) themes installed. Maybe uninstall other themes?
