### ISSUE TITLE
Proposal: ERB Ruby highlighting.

### ISSUE THREAD

**Issue by gobijan** [Monokai/monokai-pro-sublime-text#92]
Hi it would be cool to be able highlight the background of ruby code in erb html templates:

I monkey patched Monokai Pro.tmTheme like this:

    <dict>
        <key>scope</key>
        <string>source.ruby.rails.embedded.html</string>
        <key>settings</key>
        <dict>
          <key>background</key>
          <string>#231F22</string>
        </dict>
    </dict>

The result looks like this:

<img width="643" alt="bildschirmfoto 2018-09-24 um 14 30 11" src="https://user-images.githubusercontent.com/49339/45952150-5ef12980-c006-11e8-911e-1edf4882e9b8.png">

Compared to the non enhanced version:

<img width="655" alt="bildschirmfoto 2018-09-24 um 14 32 01" src="https://user-images.githubusercontent.com/49339/45952265-b1cae100-c006-11e8-9fed-014bbdd061a0.png">

What do you think @Monokai? You wanna support this modification for Monokai Pro?

**Comment by Monokai** [comment]
Thanks. I understand your idea, but I'd rather keep the background clean.
