### ISSUE TITLE
Proposal - Git changed files

### ISSUE THREAD

**Issue by AlexKvazos** [Monokai/monokai-pro-sublime-text#93]
The latest sublime dev build shows an icon on the sidebar for files that have changes (similar to how atom and vscode do it). It would be call instead of the icon you can make it so the file name changes color to something like ambar/gold. I contacted the sublime team and said that themes have this possibility.

Thanks!

**Comment by Monokai** [comment]
These styles are not in the docs yet, and Sublime HQ will update the docs in the next dev release. I did add support for the diff colors in the gutter for dev builds in 1.1.10

**Comment by krafts** [comment]
Yes please, this is much needed! I cannot stand those dots. It is more intuitive if the filename color changes.

Thanks!
