### ISSUE TITLE
Support for Mojave dark in Monokai Pro theme

### ISSUE THREAD

**Issue by dakahn** [Monokai/monokai-pro-sublime-text#94]
This is somewhere between a feature request and a bug report. But in Mojave Dark mode using the Monokai Pro theme in the latest build of Sublime Text 3 the title bar is still styled like light mode.

<img width="623" alt="screen shot 2019-01-04 at 4 11 11 pm" src="https://user-images.githubusercontent.com/40970507/50713635-5ebbed80-103b-11e9-815a-d6d4b8ff1257.png">

I can use the "adaptive" theme settings to enable dark mode support, but I prefer the flat look of Monokai Pro.

**Comment by jmdev33376** [comment]
Hi,

support for Mojave only for Sublime Text dev builds 3179+

![screen shot 2019-01-05 at 12 54 04](https://user-images.githubusercontent.com/39066958/50718962-9a14f580-10e9-11e9-8c5b-ad1755e8e173.png)


Try this in your user preferences file:

"monokai_pro_style_title_bar": true

I hope it helps.

**Comment by tobsn** [comment]
this removes the window tab bar :/

**Comment by gobijan** [comment]
I am using the latest Sublime Dev build and it adapts to darkmode. Voting to close this issue.

![screenshot 2019-01-16 at 08 34 22](https://user-images.githubusercontent.com/49339/51233187-8b400580-1969-11e9-8043-f4c442f1af85.png)

**Comment by tobsn** [comment]
open a new project.

**Comment by tobsn** [comment]
@gobijan I like your optimism but this is what happens:

Right after change & save:
![2019-01-16 at 16 45](https://user-images.githubusercontent.com/109529/51260227-22c74780-19ae-11e9-9f6b-205ac1db259c.jpg)

You see it's still visible, its getting layered behind the file tabs but it's sortof colored right and there.


After restart of Sublime:
![2019-01-16 at 16 43](https://user-images.githubusercontent.com/109529/51260170-f8758a00-19ad-11e9-9bff-7fcc1edec7e6.jpg)


The project tab bar disappears completely. It's still there, just not visible.

**Comment by Monokai** [comment]
The latest dev version of Sublime supports Mojave dark mode.
