### ISSUE TITLE
Bug: certain mark_styles in SublimeLinter don't work.

### ISSUE THREAD

**Issue by minikN** [Monokai/monokai-pro-sublime-text#95]
Hello. 

There is a bug where `"mark_style": "fill"` doesn't work with any of the Monokai Pro color schemes. You can read more about it here:

https://github.com/SublimeLinter/SublimeLinter/issues/1505

This issue doesn't seem to be related to the MonokaiPro theme, but the various color scheme variations like `Classic`, `Machine` and so on. This issue does not occur with any of the other standard sublime color schemes.

Since this only happens with Monokai Pro color schemes I reckon it's not a bug from within SublimeLinter. They were also unable to reproduce the bug.

**Comment by Monokai** [comment]
I've added the styles but I recommend not to use them. Because `"mark_style": "fill"` colors the line behind the text, I had to use a half transparent color. This makes it a bit "muddy". I would suggest not to use this and use solid_underline or indicators in the gutter instead.
