### ISSUE TITLE
sass/css parenthesis highlighting

### ISSUE THREAD

**Issue by maxime-pigeon** [Monokai/monokai-pro-sublime-text#96]
There seems to be a problem with parenthesis highlighting for some css and sass properties. See `ms(0)`(sass plugin) and `repeat(3, 1fr)`. It renders fine with ST's built-in color schemes.

<img width="694" alt="screen shot 2019-01-09 at 11 01 37 pm" src="https://user-images.githubusercontent.com/37006580/50945766-3c273b80-1464-11e9-911f-c76342d237ad.png">

**Comment by Monokai** [comment]
Fixed in 1.1.10
