### ISSUE TITLE
Italics missing for comments and such

### ISSUE THREAD

**Issue by dkrey** [Monokai/monokai-pro-sublime-text#99]
Hi,
I'm somehow missing any italics with Monokai Pro in ST3 (like keywords, comments and such), although it does work with other color schemes (like Mariana or Dracula).

In VSCode it also looks good. Is there a secret switch I am missing?

<img width="188" alt="sublime_incorrect" src="https://user-images.githubusercontent.com/11175831/53340659-da366e80-3909-11e9-941c-2fbbc8344d9e.PNG">
<img width="179" alt="vscode_correct" src="https://user-images.githubusercontent.com/11175831/53340661-da366e80-3909-11e9-867f-2fc512dc0d87.PNG">

**Comment by Monokai** [comment]
Something went wrong when I converted the old to the new scheme syntax. Totally my mistake. They're back!

**Comment by sstativa** [comment]
Can we have italic as an optional feature? 
With the font of my choice [M+ 1m Light](https://mplus-fonts.osdn.jp/about-en.html) the code looks a bit off. I'll for sure prefer the normal case to italic. 

There is also another italic issue I have, but I suppose it is fully font-related
<img width="139" alt="tab" src="https://user-images.githubusercontent.com/3362679/53710910-95738000-3e93-11e9-9194-4e0e92d94faf.png">
See how _m_ is cropped from the left in the name of the tab. Is it possible to fix it in some way?

In the past, I was altering the theme directly and removing italic completely, but it's a bit annoying to do this on every update.

Thx

**Comment by dkrey** [comment]
@Monokai Awesome, thanks a lot!
@sstativa You can disable italic fonts in the sublime settings.
Just add this to your config:
"font_options": ["no_italic"]

**Comment by sstativa** [comment]
@dkrey I did not know about this option. I tried and it worked. Thanks a lot.
